import {
  GRN_STATUS,
  QC_STATUS,
  STOCK_STATUS,
  ISSUE_STATUS,
  ADJUSTMENT_STATUS,
} from '../../utils/inventoryConstants';

// ─── MOCK FABRIC GRNs (10 records) ──────────────────────────────────────────────
export const MOCK_FABRIC_GRNS = [
  {
    id: 1,
    grnNumber: 'GRN/25-26/1001',
    type: 'Fabric',
    grnDate: '2026-03-22',
    poId: 111,
    poNumber: 'PO-FAB-2026-0111',
    supplier: 'Fabric World Inc',
    buyerName: 'Nordstrom Inc',
    styleNumber: 'AV-SS26-001',
    challanNo: 'CH-FW/8001',
    invoiceDate: '2026-03-21',
    deliveryChallanDate: '2026-03-22',
    vehicleNumber: 'TN-07-AZ-4521',
    transporter: 'Blue Dart Logistics',
    status: GRN_STATUS.DRAFT,
    remarks: 'Draft entry — work in progress',
    createdBy: 'Ranjith Kumar',
    lineItems: [
      {
        poLineItemId: 1,
        itemCode: 'FAB-CJ40-BLK',
        description: 'Cotton Jersey 40s Reactive Black',
        rolls: [
          { poLineItemId: 1, variantId: 'V-FAB-CJ40-BLK', itemCode: 'FAB-CJ40-BLK', description: 'Cotton Jersey 40s Reactive Black', width: 72, gsm: 160, poQty: 600, receivedQty: 0, balance: 600, rate: 300, uom: 'kg', rollNumber: 'D001', receivingQty: 50, shadeLot: 'SL-D-01' },
        ],
      },
    ],
  },
  {
    id: 2,
    grnNumber: 'GRN/25-26/1002',
    type: 'Fabric',
    grnDate: '2026-03-22',
    poId: 112,
    poNumber: 'PO-FAB-2026-0112',
    supplier: 'Vardhman Fabrics',
    buyerName: 'H&M Group',
    styleNumber: 'AV-SS26-005',
    challanNo: 'CH-VF-8002',
    invoiceDate: '2026-03-21',
    deliveryChallanDate: '2026-03-22',
    vehicleNumber: 'TN-39-BK-7788',
    transporter: 'DTDC Freight',
    status: GRN_STATUS.QC_PENDING,
    remarks: 'Submitted, awaiting QC',
    createdBy: 'Sathish Babu',
    lineItems: [
      {
        poLineItemId: 3,
        itemCode: 'FAB-CVCP-OLV',
        description: 'CVC Pique 220 GSM Olive',
        rolls: [
          { poLineItemId: 3, variantId: 'V-FAB-CVCP-OLV', itemCode: 'FAB-CVCP-OLV', description: 'CVC Pique 220 GSM Olive', width: 66, gsm: 220, poQty: 800, receivedQty: 0, balance: 800, rate: 350, uom: 'kg', rollNumber: 'S001', receivingQty: 75, shadeLot: 'SL-S-01' },
        ],
      },
    ],
  },
  {
    id: 3,
    grnNumber: 'GRN/25-26/1003',
    type: 'Fabric',
    grnDate: '2026-03-23',
    poId: 113,
    poNumber: 'PO-FAB-2026-0113',
    supplier: 'Arvind Mills Ltd',
    buyerName: 'Marks & Spencer',
    styleNumber: 'AV-AW26-015',
    challanNo: 'CH-AM/8003',
    invoiceDate: '2026-03-22',
    deliveryChallanDate: '2026-03-23',
    vehicleNumber: 'GJ-05-DT-9901',
    transporter: 'Safexpress',
    status: GRN_STATUS.QC_PENDING,
    remarks: 'Refer-back requested by creator',
    referBackReason: 'Need to correct receiving qty for line 1',
    createdBy: 'Ranjith Kumar',
    lineItems: [
      {
        poLineItemId: 4,
        itemCode: 'FAB-DNM-LBL',
        description: 'Light Blue Denim 8oz',
        rolls: [
          { poLineItemId: 4, variantId: 'V-FAB-DNM-LBL', itemCode: 'FAB-DNM-LBL', description: 'Light Blue Denim 8oz', width: 60, gsm: 270, poQty: 500, receivedQty: 0, balance: 500, rate: 420, uom: 'kg', rollNumber: 'RBP001', receivingQty: 90, shadeLot: 'SL-RBP-01' },
        ],
      },
    ],
  },
  {
    id: 4,
    grnNumber: 'GRN/25-26/1004',
    type: 'Fabric',
    grnDate: '2026-03-23',
    poId: 111,
    poNumber: 'PO-FAB-2026-0111',
    supplier: 'Fabric World Inc',
    buyerName: 'Nordstrom Inc',
    styleNumber: 'AV-SS26-001',
    challanNo: 'CH-FW/8004',
    invoiceDate: '2026-03-22',
    deliveryChallanDate: '2026-03-23',
    vehicleNumber: 'TN-07-AZ-4522',
    transporter: 'Blue Dart Logistics',
    status: GRN_STATUS.DRAFT,
    remarks: 'Returned for edit',
    referBackReason: 'Approved refer back — please update shade lot',
    createdBy: 'Ranjith Kumar',
    lineItems: [
      {
        poLineItemId: 2,
        itemCode: 'FAB-CJ40-GRY',
        description: 'Cotton Jersey 40s Reactive Heather Grey',
        rolls: [
          { poLineItemId: 2, variantId: 'V-FAB-CJ40-GRY', itemCode: 'FAB-CJ40-GRY', description: 'Cotton Jersey 40s Reactive Heather Grey', width: 72, gsm: 160, poQty: 400, receivedQty: 0, balance: 400, rate: 310, uom: 'kg', rollNumber: 'RB001', receivingQty: 60, shadeLot: 'SL-RB-01' },
        ],
      },
    ],
  },
  {
    id: 5,
    grnNumber: 'GRN/25-26/1005',
    type: 'Fabric',
    grnDate: '2026-03-24',
    poId: 112,
    poNumber: 'PO-FAB-2026-0112',
    supplier: 'Vardhman Fabrics',
    buyerName: 'H&M Group',
    styleNumber: 'AV-SS26-005',
    challanNo: 'CH-VF-8005',
    invoiceDate: '2026-03-23',
    deliveryChallanDate: '2026-03-24',
    vehicleNumber: 'TN-39-BK-7789',
    transporter: 'DTDC Freight',
    status: GRN_STATUS.QC_PENDING,
    remarks: 'Stock received, QC pending',
    createdBy: 'Sathish Babu',
    lineItems: [
      {
        poLineItemId: 3,
        itemCode: 'FAB-CVCP-OLV',
        description: 'CVC Pique 220 GSM Olive',
        rolls: [
          { poLineItemId: 3, variantId: 'V-FAB-CVCP-OLV', itemCode: 'FAB-CVCP-OLV', description: 'CVC Pique 220 GSM Olive', width: 66, gsm: 220, poQty: 800, receivedQty: 75, balance: 725, rate: 350, uom: 'kg', rollNumber: 'QP001', receivingQty: 80, shadeLot: 'SL-QP-01' },
          { poLineItemId: 3, variantId: 'V-FAB-CVCP-OLV', itemCode: 'FAB-CVCP-OLV', description: 'CVC Pique 220 GSM Olive', width: 66, gsm: 220, poQty: 800, receivedQty: 75, balance: 725, rate: 350, uom: 'kg', rollNumber: 'QP002', receivingQty: 78, shadeLot: 'SL-QP-01' },
        ],
      },
    ],
  },
  {
    id: 6,
    grnNumber: 'GRN/25-26/1006',
    type: 'Fabric',
    grnDate: '2026-03-24',
    poId: 113,
    poNumber: 'PO-FAB-2026-0113',
    supplier: 'Arvind Mills Ltd',
    buyerName: 'Marks & Spencer',
    styleNumber: 'AV-AW26-015',
    challanNo: 'CH-AM/8006',
    invoiceDate: '2026-03-23',
    deliveryChallanDate: '2026-03-24',
    vehicleNumber: 'GJ-05-DT-9902',
    transporter: 'Safexpress',
    status: GRN_STATUS.CLOSED,
    remarks: 'QC completed, ready to close',
    createdBy: 'Ranjith Kumar',
    lineItems: [
      {
        poLineItemId: 5,
        itemCode: 'FAB-DNM-BLK',
        description: 'Black Denim 10oz Stretch',
        rolls: [
          { poLineItemId: 5, variantId: 'V-FAB-DNM-BLK', itemCode: 'FAB-DNM-BLK', description: 'Black Denim 10oz Stretch', width: 62, gsm: 340, poQty: 450, receivedQty: 0, balance: 450, rate: 450, uom: 'kg', rollNumber: 'QC001', receivingQty: 95, shadeLot: 'SL-QC-01' },
        ],
      },
    ],
  },
  {
    id: 7,
    grnNumber: 'GRN/25-26/1007',
    type: 'Fabric',
    grnDate: '2026-03-25',
    poId: 111,
    poNumber: 'PO-FAB-2026-0111',
    supplier: 'Fabric World Inc',
    buyerName: 'Nordstrom Inc',
    styleNumber: 'AV-SS26-001',
    challanNo: 'CH-FW/8007',
    invoiceDate: '2026-03-24',
    deliveryChallanDate: '2026-03-25',
    vehicleNumber: 'TN-07-AZ-4523',
    transporter: 'Blue Dart Logistics',
    status: GRN_STATUS.CLOSED,
    remarks: 'Closed and stocked',
    createdBy: 'Ranjith Kumar',
    lineItems: [
      {
        poLineItemId: 1,
        itemCode: 'FAB-CJ40-BLK',
        description: 'Cotton Jersey 40s Reactive Black',
        rolls: [
          { poLineItemId: 1, variantId: 'V-FAB-CJ40-BLK', itemCode: 'FAB-CJ40-BLK', description: 'Cotton Jersey 40s Reactive Black', width: 72, gsm: 160, poQty: 600, receivedQty: 50, balance: 550, rate: 300, uom: 'kg', rollNumber: 'CL001', receivingQty: 70, shadeLot: 'SL-CL-01' },
        ],
      },
    ],
  },
  {
    id: 8,
    grnNumber: 'GRN/25-26/1008',
    type: 'Fabric',
    grnDate: '2026-03-25',
    poId: 112,
    poNumber: 'PO-FAB-2026-0112',
    supplier: 'Vardhman Fabrics',
    buyerName: 'H&M Group',
    styleNumber: 'AV-SS26-005',
    challanNo: 'CH-VF-8008',
    invoiceDate: '2026-03-24',
    deliveryChallanDate: '2026-03-25',
    vehicleNumber: 'TN-39-BK-7790',
    transporter: 'DTDC Freight',
    status: GRN_STATUS.QC_PENDING,
    remarks: 'Reversal requested',
    reversalReason: 'Wrong PO line was used — needs reversal',
    createdBy: 'Sathish Babu',
    lineItems: [
      {
        poLineItemId: 3,
        itemCode: 'FAB-CVCP-OLV',
        description: 'CVC Pique 220 GSM Olive',
        rolls: [
          { poLineItemId: 3, variantId: 'V-FAB-CVCP-OLV', itemCode: 'FAB-CVCP-OLV', description: 'CVC Pique 220 GSM Olive', width: 66, gsm: 220, poQty: 800, receivedQty: 233, balance: 567, rate: 350, uom: 'kg', rollNumber: 'PR001', receivingQty: 65, shadeLot: 'SL-PR-01' },
        ],
      },
    ],
  },
  {
    id: 9,
    grnNumber: 'GRN/25-26/1009',
    type: 'Fabric',
    grnDate: '2026-03-26',
    poId: 113,
    poNumber: 'PO-FAB-2026-0113',
    supplier: 'Arvind Mills Ltd',
    buyerName: 'Marks & Spencer',
    styleNumber: 'AV-AW26-015',
    challanNo: 'CH-AM/8009',
    invoiceDate: '2026-03-25',
    deliveryChallanDate: '2026-03-26',
    vehicleNumber: 'GJ-05-DT-9903',
    transporter: 'Safexpress',
    status: GRN_STATUS.REVERSED,
    remarks: 'Reversal approved',
    reversalReason: 'Approved by manager — receipt reversed',
    createdBy: 'Ranjith Kumar',
    lineItems: [
      {
        poLineItemId: 4,
        itemCode: 'FAB-DNM-LBL',
        description: 'Light Blue Denim 8oz',
        rolls: [
          { poLineItemId: 4, variantId: 'V-FAB-DNM-LBL', itemCode: 'FAB-DNM-LBL', description: 'Light Blue Denim 8oz', width: 60, gsm: 270, poQty: 500, receivedQty: 90, balance: 410, rate: 420, uom: 'kg', rollNumber: 'RV001', receivingQty: 85, shadeLot: 'SL-RV-01' },
        ],
      },
    ],
  },
  // ── Extra Submitted records (QC preview padding) — richer line items, multiple rolls ──
  {
    id: 10,
    grnNumber: 'GRN/25-26/1010',
    type: 'Fabric',
    grnDate: '2026-03-27',
    poId: 111,
    poNumber: 'PO-FAB-2026-0111',
    supplier: 'Fabric World Inc',
    buyerName: 'Nordstrom Inc',
    styleNumber: 'AV-SS26-001',
    challanNo: 'CH-FW/8010',
    invoiceDate: '2026-03-26',
    deliveryChallanDate: '2026-03-27',
    vehicleNumber: 'TN-07-AZ-4525',
    transporter: 'Blue Dart Logistics',
    status: GRN_STATUS.QC_PENDING,
    remarks: 'Large lot — 2 line items, 4 rolls total',
    createdBy: 'Ranjith Kumar',
    lineItems: [
      {
        poLineItemId: 1,
        itemCode: 'FAB-CJ40-BLK',
        description: 'Cotton Jersey 40s Reactive Black',
        rolls: [
          { poLineItemId: 1, variantId: 'V-FAB-CJ40-BLK', itemCode: 'FAB-CJ40-BLK', description: 'Cotton Jersey 40s Reactive Black', width: 72, gsm: 160, poQty: 600, receivedQty: 120, balance: 480, rate: 300, uom: 'kg', rollNumber: 'S-010-001', receivingQty: 58, shadeLot: 'SL-S10-A' },
          { poLineItemId: 1, variantId: 'V-FAB-CJ40-BLK', itemCode: 'FAB-CJ40-BLK', description: 'Cotton Jersey 40s Reactive Black', width: 72, gsm: 160, poQty: 600, receivedQty: 120, balance: 480, rate: 300, uom: 'kg', rollNumber: 'S-010-002', receivingQty: 62, shadeLot: 'SL-S10-A' },
        ],
      },
      {
        poLineItemId: 2,
        itemCode: 'FAB-CJ40-GRY',
        description: 'Cotton Jersey 40s Reactive Heather Grey',
        rolls: [
          { poLineItemId: 2, variantId: 'V-FAB-CJ40-GRY', itemCode: 'FAB-CJ40-GRY', description: 'Cotton Jersey 40s Reactive Heather Grey', width: 72, gsm: 160, poQty: 400, receivedQty: 60, balance: 340, rate: 310, uom: 'kg', rollNumber: 'S-010-101', receivingQty: 55, shadeLot: 'SL-S10-B' },
          { poLineItemId: 2, variantId: 'V-FAB-CJ40-GRY', itemCode: 'FAB-CJ40-GRY', description: 'Cotton Jersey 40s Reactive Heather Grey', width: 72, gsm: 160, poQty: 400, receivedQty: 60, balance: 340, rate: 310, uom: 'kg', rollNumber: 'S-010-102', receivingQty: 60, shadeLot: 'SL-S10-B' },
        ],
      },
    ],
  },
  {
    id: 11,
    grnNumber: 'GRN/25-26/1011',
    type: 'Fabric',
    grnDate: '2026-03-28',
    poId: 113,
    poNumber: 'PO-FAB-2026-0113',
    supplier: 'Arvind Mills Ltd',
    buyerName: 'Marks & Spencer',
    styleNumber: 'AV-AW26-015',
    challanNo: 'CH-AM/8011',
    invoiceDate: '2026-03-27',
    deliveryChallanDate: '2026-03-28',
    vehicleNumber: 'GJ-05-DT-9905',
    transporter: 'Safexpress',
    status: GRN_STATUS.QC_PENDING,
    remarks: 'Denim lot — 3 rolls, ready for QC',
    createdBy: 'Sathish Babu',
    lineItems: [
      {
        poLineItemId: 5,
        itemCode: 'FAB-DNM-BLK',
        description: 'Black Denim 10oz Stretch',
        rolls: [
          { poLineItemId: 5, variantId: 'V-FAB-DNM-BLK', itemCode: 'FAB-DNM-BLK', description: 'Black Denim 10oz Stretch', width: 62, gsm: 340, poQty: 450, receivedQty: 95, balance: 355, rate: 450, uom: 'kg', rollNumber: 'S-011-001', receivingQty: 88, shadeLot: 'SL-S11-A' },
          { poLineItemId: 5, variantId: 'V-FAB-DNM-BLK', itemCode: 'FAB-DNM-BLK', description: 'Black Denim 10oz Stretch', width: 62, gsm: 340, poQty: 450, receivedQty: 95, balance: 355, rate: 450, uom: 'kg', rollNumber: 'S-011-002', receivingQty: 92, shadeLot: 'SL-S11-A' },
          { poLineItemId: 5, variantId: 'V-FAB-DNM-BLK', itemCode: 'FAB-DNM-BLK', description: 'Black Denim 10oz Stretch', width: 62, gsm: 340, poQty: 450, receivedQty: 95, balance: 355, rate: 450, uom: 'kg', rollNumber: 'S-011-003', receivingQty: 85, shadeLot: 'SL-S11-B' },
        ],
      },
    ],
  },
];

// ─── MOCK ACCESSORIES GRNs (8 records) ──────────────────────────────────────────
export const MOCK_ACCESSORIES_GRNS = [
  {
    id: 101,
    grnNumber: 'GRN/25-26/2001',
    type: 'Accessories',
    grnDate: '2026-03-22',
    poId: 214,
    poNumber: 'PO-ACC-2026-0209',
    supplier: 'Button Bazaar',
    buyerName: 'Nordstrom Inc',
    styleNumber: 'AV-AW26-015',
    challanNo: 'CH-BB/9001',
    invoiceDate: '2026-03-21',
    deliveryChallanDate: '2026-03-22',
    vehicleNumber: 'DL-01-YZ-7788',
    transporter: 'DTDC Freight',
    status: GRN_STATUS.DRAFT,
    remarks: 'Draft trims entry',
    createdBy: 'Priya Sharma',
    lineItems: [6],
    items: [
      { poLineItemId: 6, variantId: 'V-BTN-4H-20MM-BRN', itemCode: 'BTN-4H-20MM-BRN', description: '4-Hole Horn Button 20mm Brown', color: 'Brown', size: '20mm', poQty: 10000, alreadyReceived: 0, balance: 10000, receivingQty: 1000, uom: 'pcs', rate: 3.5 },
    ],
    cartons: [
      { poLineItemId: 6, cartonNumber: 'D-C001', itemCode: 'BTN-4H-20MM-BRN', itemDescription: '4-Hole Horn Button 20mm Brown', color: 'Brown', size: '20mm', quantity: 7, uom: 'gross' },
    ],
  },
  {
    id: 102,
    grnNumber: 'GRN/25-26/2002',
    type: 'Accessories',
    grnDate: '2026-03-22',
    poId: 215,
    poNumber: 'PO-ACC-2026-0210',
    supplier: 'Zipper King Exports',
    buyerName: 'H&M Group',
    styleNumber: 'AV-AW26-015',
    challanNo: 'CH-ZK-9002',
    invoiceDate: '2026-03-21',
    deliveryChallanDate: '2026-03-22',
    vehicleNumber: 'MH-12-QW-3344',
    transporter: 'Blue Dart Logistics',
    status: GRN_STATUS.QC_PENDING,
    remarks: 'Submitted, awaiting QC',
    createdBy: 'Priya Sharma',
    lineItems: [8],
    items: [
      { poLineItemId: 8, variantId: 'V-ZIP-YKK-50CM-BLK', itemCode: 'ZIP-YKK-50CM-BLK', description: 'YKK Metal Zipper 50cm Black', color: 'Black', size: '50cm', poQty: 2000, alreadyReceived: 0, balance: 2000, receivingQty: 1000, uom: 'pcs', rate: 25 },
    ],
    cartons: [
      { poLineItemId: 8, cartonNumber: 'S-C001', itemCode: 'ZIP-YKK-50CM-BLK', itemDescription: 'YKK Metal Zipper 50cm Black', color: 'Black', size: '50cm', quantity: 84, uom: 'dozen' },
    ],
  },
  {
    id: 103,
    grnNumber: 'GRN/25-26/2003',
    type: 'Accessories',
    grnDate: '2026-03-23',
    poId: 216,
    poNumber: 'PO-ACC-2026-0211',
    supplier: 'Pacific Trims Co',
    buyerName: 'Marks & Spencer',
    styleNumber: 'AV-SS26-008',
    challanNo: 'CH-PT/9003',
    invoiceDate: '2026-03-22',
    deliveryChallanDate: '2026-03-23',
    vehicleNumber: 'KA-01-MN-3344',
    transporter: 'Gati Kintetsu',
    status: GRN_STATUS.QC_PENDING,
    remarks: 'Refer-back requested',
    referBackReason: 'Quantity mismatch with DC — needs correction',
    createdBy: 'Priya Sharma',
    lineItems: [9],
    items: [
      { poLineItemId: 9, variantId: 'V-ELS-38MM-BLK-LOGO', itemCode: 'ELS-38MM-BLK-LOGO', description: 'Jacquard Elastic 38mm Black with Logo', color: 'Black', size: '38mm', poQty: 3000, alreadyReceived: 0, balance: 3000, receivingQty: 500, uom: 'meters', rate: 12 },
    ],
    cartons: [
      { poLineItemId: 9, cartonNumber: 'RBP-C001', itemCode: 'ELS-38MM-BLK-LOGO', itemDescription: 'Jacquard Elastic 38mm Black with Logo', color: 'Black', size: '38mm', quantity: 5, uom: 'rolls' },
    ],
  },
  {
    id: 104,
    grnNumber: 'GRN/25-26/2004',
    type: 'Accessories',
    grnDate: '2026-03-23',
    poId: 214,
    poNumber: 'PO-ACC-2026-0209',
    supplier: 'Button Bazaar',
    buyerName: 'Nordstrom Inc',
    styleNumber: 'AV-AW26-015',
    challanNo: 'CH-BB/9004',
    invoiceDate: '2026-03-22',
    deliveryChallanDate: '2026-03-23',
    vehicleNumber: 'DL-01-YZ-7789',
    transporter: 'DTDC Freight',
    status: GRN_STATUS.DRAFT,
    remarks: 'Returned for edit',
    referBackReason: 'Approved refer back — please verify carton count',
    createdBy: 'Priya Sharma',
    lineItems: [7],
    items: [
      { poLineItemId: 7, variantId: 'V-BTN-SHANK-15MM-GLD', itemCode: 'BTN-SHANK-15MM-GLD', description: 'Shank Button 15mm Gold', color: 'Gold', size: '15mm', poQty: 5000, alreadyReceived: 0, balance: 5000, receivingQty: 1500, uom: 'pcs', rate: 4 },
    ],
    cartons: [
      { poLineItemId: 7, cartonNumber: 'RB-C001', itemCode: 'BTN-SHANK-15MM-GLD', itemDescription: 'Shank Button 15mm Gold', color: 'Gold', size: '15mm', quantity: 11, uom: 'gross' },
    ],
  },
  {
    id: 105,
    grnNumber: 'GRN/25-26/2005',
    type: 'Accessories',
    grnDate: '2026-03-24',
    poId: 215,
    poNumber: 'PO-ACC-2026-0210',
    supplier: 'Zipper King Exports',
    buyerName: 'H&M Group',
    styleNumber: 'AV-AW26-015',
    challanNo: 'CH-ZK-9005',
    invoiceDate: '2026-03-23',
    deliveryChallanDate: '2026-03-24',
    vehicleNumber: 'MH-12-QW-3345',
    transporter: 'Blue Dart Logistics',
    status: GRN_STATUS.QC_PENDING,
    remarks: 'QC pending',
    createdBy: 'Priya Sharma',
    lineItems: [8],
    items: [
      { poLineItemId: 8, variantId: 'V-ZIP-YKK-50CM-BLK', itemCode: 'ZIP-YKK-50CM-BLK', description: 'YKK Metal Zipper 50cm Black', color: 'Black', size: '50cm', poQty: 2000, alreadyReceived: 1000, balance: 1000, receivingQty: 600, uom: 'pcs', rate: 25 },
    ],
    cartons: [
      { poLineItemId: 8, cartonNumber: 'QP-C001', itemCode: 'ZIP-YKK-50CM-BLK', itemDescription: 'YKK Metal Zipper 50cm Black', color: 'Black', size: '50cm', quantity: 50, uom: 'dozen' },
    ],
  },
  {
    id: 106,
    grnNumber: 'GRN/25-26/2006',
    type: 'Accessories',
    grnDate: '2026-03-24',
    poId: 216,
    poNumber: 'PO-ACC-2026-0211',
    supplier: 'Pacific Trims Co',
    buyerName: 'Marks & Spencer',
    styleNumber: 'AV-SS26-008',
    challanNo: 'CH-PT/9006',
    invoiceDate: '2026-03-23',
    deliveryChallanDate: '2026-03-24',
    vehicleNumber: 'KA-01-MN-3345',
    transporter: 'Gati Kintetsu',
    status: GRN_STATUS.CLOSED,
    remarks: 'QC complete, ready to close',
    createdBy: 'Priya Sharma',
    lineItems: [10],
    items: [
      { poLineItemId: 10, variantId: 'V-DRW-CORD-5MM-BLK', itemCode: 'DRW-CORD-5MM-BLK', description: 'Drawcord Round 5mm Black', color: 'Black', size: '5mm', poQty: 2000, alreadyReceived: 0, balance: 2000, receivingQty: 1000, uom: 'meters', rate: 4 },
    ],
    cartons: [
      { poLineItemId: 10, cartonNumber: 'QC-C001', itemCode: 'DRW-CORD-5MM-BLK', itemDescription: 'Drawcord Round 5mm Black', color: 'Black', size: '5mm', quantity: 10, uom: 'rolls' },
    ],
  },
  {
    id: 107,
    grnNumber: 'GRN/25-26/2007',
    type: 'Accessories',
    grnDate: '2026-03-25',
    poId: 214,
    poNumber: 'PO-ACC-2026-0209',
    supplier: 'Button Bazaar',
    buyerName: 'Nordstrom Inc',
    styleNumber: 'AV-AW26-015',
    challanNo: 'CH-BB/9007',
    invoiceDate: '2026-03-24',
    deliveryChallanDate: '2026-03-25',
    vehicleNumber: 'DL-01-YZ-7790',
    transporter: 'DTDC Freight',
    status: GRN_STATUS.CLOSED,
    remarks: 'Closed and stocked',
    createdBy: 'Priya Sharma',
    lineItems: [6],
    items: [
      { poLineItemId: 6, variantId: 'V-BTN-4H-20MM-BRN', itemCode: 'BTN-4H-20MM-BRN', description: '4-Hole Horn Button 20mm Brown', color: 'Brown', size: '20mm', poQty: 10000, alreadyReceived: 1000, balance: 9000, receivingQty: 4000, uom: 'pcs', rate: 3.5 },
    ],
    cartons: [
      { poLineItemId: 6, cartonNumber: 'CL-C001', itemCode: 'BTN-4H-20MM-BRN', itemDescription: '4-Hole Horn Button 20mm Brown', color: 'Brown', size: '20mm', quantity: 28, uom: 'gross' },
    ],
  },
  {
    id: 108,
    grnNumber: 'GRN/25-26/2008',
    type: 'Accessories',
    grnDate: '2026-03-25',
    poId: 215,
    poNumber: 'PO-ACC-2026-0210',
    supplier: 'Zipper King Exports',
    buyerName: 'H&M Group',
    styleNumber: 'AV-AW26-015',
    challanNo: 'CH-ZK-9008',
    invoiceDate: '2026-03-24',
    deliveryChallanDate: '2026-03-25',
    vehicleNumber: 'MH-12-QW-3346',
    transporter: 'Blue Dart Logistics',
    status: GRN_STATUS.QC_PENDING,
    remarks: 'Reversal requested',
    reversalReason: 'Wrong supplier referenced — needs reversal',
    createdBy: 'Priya Sharma',
    lineItems: [8],
    items: [
      { poLineItemId: 8, variantId: 'V-ZIP-YKK-50CM-BLK', itemCode: 'ZIP-YKK-50CM-BLK', description: 'YKK Metal Zipper 50cm Black', color: 'Black', size: '50cm', poQty: 2000, alreadyReceived: 1600, balance: 400, receivingQty: 200, uom: 'pcs', rate: 25 },
    ],
    cartons: [
      { poLineItemId: 8, cartonNumber: 'PR-C001', itemCode: 'ZIP-YKK-50CM-BLK', itemDescription: 'YKK Metal Zipper 50cm Black', color: 'Black', size: '50cm', quantity: 17, uom: 'dozen' },
    ],
  },
  {
    id: 109,
    grnNumber: 'GRN/25-26/2009',
    type: 'Accessories',
    grnDate: '2026-03-26',
    poId: 216,
    poNumber: 'PO-ACC-2026-0211',
    supplier: 'Pacific Trims Co',
    buyerName: 'Marks & Spencer',
    styleNumber: 'AV-SS26-008',
    challanNo: 'CH-PT/9009',
    invoiceDate: '2026-03-25',
    deliveryChallanDate: '2026-03-26',
    vehicleNumber: 'KA-01-MN-3346',
    transporter: 'Gati Kintetsu',
    status: GRN_STATUS.REVERSED,
    remarks: 'Reversal approved',
    reversalReason: 'Approved by manager — receipt reversed',
    createdBy: 'Priya Sharma',
    lineItems: [9],
    items: [
      { poLineItemId: 9, variantId: 'V-ELS-38MM-BLK-LOGO', itemCode: 'ELS-38MM-BLK-LOGO', description: 'Jacquard Elastic 38mm Black with Logo', color: 'Black', size: '38mm', poQty: 3000, alreadyReceived: 500, balance: 2500, receivingQty: 800, uom: 'meters', rate: 12 },
    ],
    cartons: [
      { poLineItemId: 9, cartonNumber: 'RV-C001', itemCode: 'ELS-38MM-BLK-LOGO', itemDescription: 'Jacquard Elastic 38mm Black with Logo', color: 'Black', size: '38mm', quantity: 8, uom: 'rolls' },
    ],
  },
  // ── Extra Submitted records (QC preview padding) — multi-item, multi-carton ──
  {
    id: 110,
    grnNumber: 'GRN/25-26/2010',
    type: 'Accessories',
    grnDate: '2026-03-27',
    poId: 214,
    poNumber: 'PO-ACC-2026-0209',
    supplier: 'Button Bazaar',
    buyerName: 'Nordstrom Inc',
    styleNumber: 'AV-AW26-015',
    challanNo: 'CH-BB/9010',
    invoiceDate: '2026-03-26',
    deliveryChallanDate: '2026-03-27',
    vehicleNumber: 'DL-01-YZ-7795',
    transporter: 'DTDC Freight',
    status: GRN_STATUS.QC_PENDING,
    remarks: 'Trim lot — 2 SKUs, 3 cartons',
    createdBy: 'Priya Sharma',
    lineItems: [6, 7],
    items: [
      { poLineItemId: 6, variantId: 'V-BTN-4H-20MM-BRN', itemCode: 'BTN-4H-20MM-BRN', description: '4-Hole Horn Button 20mm Brown', color: 'Brown', size: '20mm', poQty: 10000, alreadyReceived: 2500, balance: 7500, receivingQty: 2000, uom: 'pcs', rate: 3.5 },
      { poLineItemId: 7, variantId: 'V-BTN-SH-15MM-IVY', itemCode: 'BTN-SH-15MM-IVY', description: 'Shank Button 15mm Ivory', color: 'Ivory', size: '15mm', poQty: 8000, alreadyReceived: 1000, balance: 7000, receivingQty: 1500, uom: 'pcs', rate: 2.8 },
    ],
    cartons: [
      { poLineItemId: 6, cartonNumber: 'S-110-C001', itemCode: 'BTN-4H-20MM-BRN', itemDescription: '4-Hole Horn Button 20mm Brown', color: 'Brown', size: '20mm', quantity: 8, uom: 'gross' },
      { poLineItemId: 6, cartonNumber: 'S-110-C002', itemCode: 'BTN-4H-20MM-BRN', itemDescription: '4-Hole Horn Button 20mm Brown', color: 'Brown', size: '20mm', quantity: 6, uom: 'gross' },
      { poLineItemId: 7, cartonNumber: 'S-110-C101', itemCode: 'BTN-SH-15MM-IVY', itemDescription: 'Shank Button 15mm Ivory', color: 'Ivory', size: '15mm', quantity: 10, uom: 'gross' },
    ],
  },
  {
    id: 111,
    grnNumber: 'GRN/25-26/2011',
    type: 'Accessories',
    grnDate: '2026-03-28',
    poId: 215,
    poNumber: 'PO-ACC-2026-0210',
    supplier: 'Metro Labels',
    buyerName: 'H&M Group',
    styleNumber: 'AV-SS26-005',
    challanNo: 'CH-ML/9011',
    invoiceDate: '2026-03-27',
    deliveryChallanDate: '2026-03-28',
    vehicleNumber: 'MH-14-PQ-3301',
    transporter: 'Safexpress',
    status: GRN_STATUS.QC_PENDING,
    remarks: 'Woven label lot — 2 cartons, ready for QC',
    createdBy: 'Priya Sharma',
    lineItems: [8],
    items: [
      { poLineItemId: 8, variantId: 'V-LBL-WVN-MAIN', itemCode: 'LBL-WVN-MAIN', description: 'Woven Main Label — H&M SS26', color: 'Black/White', size: '40x25mm', poQty: 20000, alreadyReceived: 5000, balance: 15000, receivingQty: 4000, uom: 'pcs', rate: 0.85 },
    ],
    cartons: [
      { poLineItemId: 8, cartonNumber: 'S-111-C001', itemCode: 'LBL-WVN-MAIN', itemDescription: 'Woven Main Label — H&M SS26', color: 'Black/White', size: '40x25mm', quantity: 10, uom: 'packs' },
      { poLineItemId: 8, cartonNumber: 'S-111-C002', itemCode: 'LBL-WVN-MAIN', itemDescription: 'Woven Main Label — H&M SS26', color: 'Black/White', size: '40x25mm', quantity: 10, uom: 'packs' },
    ],
  },
];

// ─── MOCK FABRIC QC (6 records) ─────────────────────────────────────────────────
// ─── MOCK FABRIC QC ────────────────────────────────────────────────────────────
// Normalised shape (A1/A6/A7):
//   - `parameters` is a row-array: [{ key, label, unit, standard?, actual, result? }]
//     Ratings (shadeMatch etc.) have `actual` only, no standard/result.
//     Shrinkage has `actual` percentage only.
//     Numeric params (gsm, width, tensileStrength) have standard + actual + computed result.
//   - `defects` has only the 5 fields the new UI reads: rollNumber, defectTypeId, defectTypeName, count, remarks.
//     Legacy defectSize / points / location / totalDefectPoints / pointsPer100SqYd dropped.
//   - Status values use only the 7 new values (Draft, Submitted, Pending_Approval, Approved, Rejected,
//     Referred_Back_Pending, Referred_Back). Legacy Passed/Failed/In_Progress/Conditional mapped to new ones.
//   - Added `version` field (optimistic lock placeholder for when API lands).
//
// Mock records intentionally leave `defectTypeId: null` — real defect type ids come from the
// backend-seeded /defect-types master. The UI's defect dropdown sources from `getActiveDefectTypes()`
// so historical mock defects render by name but can't be re-edited to match an exact master row.
export const MOCK_FABRIC_QC = [
  {
    id: 1,
    qcNumber: 'FQC-2026-0001',
    version: 0,
    grnId: 1,
    grnNumber: 'GRN-F-2026-0001',
    poLineItemId: 1,
    fabricDescription: 'Cotton Jersey 40s Reactive',
    rollCount: 12,
    inspector: 'Karthik Raman',
    inspectionDate: '2026-03-11',
    status: QC_STATUS.APPROVED,
    submittedAt: '2026-03-11T14:30:00Z',
    parameters: [
      { key: 'gsm',               label: 'GSM (Weight)',            unit: 'g/m²',       standard: 160, actual: 160.5, result: 'Pass' },
      { key: 'width',             label: 'Width',                   unit: 'inches',     standard: 72,  actual: 71.8,  result: 'Pass' },
      { key: 'shadeMatch',        label: 'Shade Variation',         unit: 'Grade 1-5',  actual: 4 },
      { key: 'shrinkageLength',   label: 'Shrinkage (Length)',      unit: '%',          actual: -3.2 },
      { key: 'shrinkageWidth',    label: 'Shrinkage (Width)',       unit: '%',          actual: -2.8 },
      { key: 'colorFastnessWash', label: 'Color Fastness (Wash)',   unit: 'Grade 1-5',  actual: 4 },
      { key: 'colorFastnessRub',  label: 'Color Fastness (Rubbing)',unit: 'Grade 1-5',  actual: 4 },
      { key: 'pillingResistance', label: 'Pilling Resistance',      unit: 'Grade 1-5',  actual: 4 },
      { key: 'tensileStrength',   label: 'Tensile Strength',        unit: 'N',          standard: 280, actual: 285,   result: 'Pass' },
    ],
    defects: [
      { rollNumber: 'R003', defectTypeId: null, defectTypeName: 'Slub',     count: 1, remarks: 'Minor — acceptable' },
      { rollNumber: 'R007', defectTypeId: null, defectTypeName: 'Oil Spot', count: 1, remarks: 'Small spot — edge area' },
    ],
    overallResult: 'Pass',
    approver: 'Meena Sundaram',
    approverRole: 'Fabric Coordinator',
    approvalStatus: 'Approved',
    approvalReason: 'Within acceptable tolerance. Approved for cutting.',
    rejectionReason: null,
    referBackReason: null,
  },
  {
    id: 2,
    qcNumber: 'FQC-2026-0002',
    version: 0,
    grnId: 2,
    grnNumber: 'GRN-F-2026-0002',
    poLineItemId: 3,
    fabricDescription: '100% Polyester Satin 75D',
    rollCount: 8,
    inspector: 'Karthik Raman',
    inspectionDate: '2026-03-13',
    status: QC_STATUS.PENDING_APPROVAL,
    submittedAt: '2026-03-13T10:15:00Z',
    parameters: [
      { key: 'gsm',               label: 'GSM (Weight)',            unit: 'g/m²',       standard: 95, actual: 95.2, result: 'Pass' },
      { key: 'width',             label: 'Width',                   unit: 'inches',     standard: 58, actual: 57.6, result: 'Pass' },
      { key: 'shadeMatch',        label: 'Shade Variation',         unit: 'Grade 1-5',  actual: 3 },
      { key: 'shrinkageLength',   label: 'Shrinkage (Length)',      unit: '%',          actual: -1.5 },
      { key: 'shrinkageWidth',    label: 'Shrinkage (Width)',       unit: '%',          actual: -1.2 },
      { key: 'colorFastnessWash', label: 'Color Fastness (Wash)',   unit: 'Grade 1-5',  actual: 4 },
      { key: 'colorFastnessRub',  label: 'Color Fastness (Rubbing)',unit: 'Grade 1-5',  actual: 3 },
      { key: 'pillingResistance', label: 'Pilling Resistance',      unit: 'Grade 1-5',  actual: 5 },
      { key: 'tensileStrength',   label: 'Tensile Strength',        unit: 'N',          standard: 320, actual: 318, result: 'Pass' },
    ],
    defects: [
      { rollNumber: 'R003', defectTypeId: null, defectTypeName: 'Shade Bar',   count: 2, remarks: 'Visible shade band' },
      { rollNumber: 'R004', defectTypeId: null, defectTypeName: 'Shade Bar',   count: 2, remarks: 'Similar shade band as R003' },
      { rollNumber: 'R006', defectTypeId: null, defectTypeName: 'Crease Mark', count: 1, remarks: 'Light crease' },
    ],
    overallResult: 'Pass',
    approver: null,
    approverRole: 'Fabric Coordinator',
    approvalStatus: 'Pending',
    approvalReason: null,
    rejectionReason: null,
    referBackReason: null,
  },
  {
    id: 3,
    qcNumber: 'FQC-2026-0003',
    version: 0,
    grnId: 3,
    grnNumber: 'GRN-F-2026-0003',
    poLineItemId: 4,
    fabricDescription: 'CVC Pique 220 GSM',
    rollCount: 15,
    inspector: 'Deepa Krishnan',
    inspectionDate: '2026-03-15',
    // Refer-back flow: this QC was approved earlier; a senior manager then requested
    // it be reopened for re-inspection of a specific roll. Status sits here until a
    // second approver actions the request.
    status: QC_STATUS.REFERRED_BACK_PENDING,
    submittedAt: '2026-03-15T09:00:00Z',
    parameters: [
      { key: 'gsm',               label: 'GSM (Weight)',            unit: 'g/m²',       standard: 220, actual: 220.3, result: 'Pass' },
      { key: 'width',             label: 'Width',                   unit: 'inches',     standard: 66,  actual: 66.1,  result: 'Pass' },
      { key: 'shadeMatch',        label: 'Shade Variation',         unit: 'Grade 1-5',  actual: 4 },
      { key: 'shrinkageLength',   label: 'Shrinkage (Length)',      unit: '%',          actual: -2.8 },
      { key: 'shrinkageWidth',    label: 'Shrinkage (Width)',       unit: '%',          actual: -2.5 },
      { key: 'colorFastnessWash', label: 'Color Fastness (Wash)',   unit: 'Grade 1-5',  actual: 4 },
      { key: 'colorFastnessRub',  label: 'Color Fastness (Rubbing)',unit: 'Grade 1-5',  actual: 4 },
      { key: 'pillingResistance', label: 'Pilling Resistance',      unit: 'Grade 1-5',  actual: 4 },
      { key: 'tensileStrength',   label: 'Tensile Strength',        unit: 'N',          standard: 310, actual: 315, result: 'Pass' },
    ],
    defects: [
      { rollNumber: 'R009', defectTypeId: null, defectTypeName: 'Broken End', count: 1, remarks: 'Single broken end — minor' },
    ],
    overallResult: 'Pass',
    approver: 'Meena Sundaram',
    approverRole: 'Fabric Coordinator',
    approvalStatus: 'Approved',
    approvalReason: 'Excellent quality. Cleared for production.',
    rejectionReason: null,
    referBackReason: 'Roll R009 needs re-check — customer raised a shade concern on a sample.',
  },
  {
    id: 4,
    qcNumber: 'FQC-2026-0004',
    version: 0,
    grnId: 8,
    grnNumber: 'GRN-F-2026-0008',
    poLineItemId: 5,
    fabricDescription: 'Indigo Denim 10oz Stretch',
    rollCount: 10,
    inspector: 'Karthik Raman',
    inspectionDate: '2026-03-23',
    // Refer-back has been approved — QC is now editable again by the creator.
    status: QC_STATUS.REFERRED_BACK,
    submittedAt: '2026-03-23T11:45:00Z',
    parameters: [
      { key: 'gsm',               label: 'GSM (Weight)',            unit: 'g/m²',       standard: 340, actual: 339.5, result: 'Pass' },
      { key: 'width',             label: 'Width',                   unit: 'inches',     standard: 62,  actual: 62.2,  result: 'Pass' },
      { key: 'shadeMatch',        label: 'Shade Variation',         unit: 'Grade 1-5',  actual: 4 },
      { key: 'shrinkageLength',   label: 'Shrinkage (Length)',      unit: '%',          actual: -3.5 },
      { key: 'shrinkageWidth',    label: 'Shrinkage (Width)',       unit: '%',          actual: -2.0 },
      { key: 'colorFastnessWash', label: 'Color Fastness (Wash)',   unit: 'Grade 1-5',  actual: 3 },
      { key: 'colorFastnessRub',  label: 'Color Fastness (Rubbing)',unit: 'Grade 1-5',  actual: 3 },
      { key: 'pillingResistance', label: 'Pilling Resistance',      unit: 'Grade 1-5',  actual: 5 },
      { key: 'tensileStrength',   label: 'Tensile Strength',        unit: 'N',          standard: 450, actual: 455, result: 'Pass' },
    ],
    defects: [
      { rollNumber: 'R005', defectTypeId: null, defectTypeName: 'Selvage Defect', count: 1, remarks: 'Tight selvage — within usable area' },
      { rollNumber: 'R009', defectTypeId: null, defectTypeName: 'Missing Pick',   count: 1, remarks: 'Minor pick out' },
    ],
    overallResult: 'Pass',
    approver: 'Meena Sundaram',
    approverRole: 'Fabric Coordinator',
    approvalStatus: 'Approved',
    approvalReason: 'Good denim quality. Approved for jacket production.',
    rejectionReason: null,
    referBackReason: 'Refer-back approved — re-inspect rolls R005 and R009 before cutting.',
  },
  {
    id: 5,
    qcNumber: 'FQC-2026-0005',
    version: 0,
    grnId: 9,
    grnNumber: 'GRN-F-2026-0009',
    poLineItemId: 6,
    fabricDescription: 'Linen Cotton Blend 55/45',
    rollCount: 7,
    inspector: 'Deepa Krishnan',
    inspectionDate: '2026-03-25',
    // Legacy FAILED → REJECTED
    status: QC_STATUS.REJECTED,
    submittedAt: '2026-03-25T16:00:00Z',
    parameters: [
      { key: 'gsm',               label: 'GSM (Weight)',            unit: 'g/m²',       standard: 150, actual: 142.0, result: 'Fail' },
      { key: 'width',             label: 'Width',                   unit: 'inches',     standard: 56,  actual: 55.2,  result: 'Pass' },
      { key: 'shadeMatch',        label: 'Shade Variation',         unit: 'Grade 1-5',  actual: 2 },
      { key: 'shrinkageLength',   label: 'Shrinkage (Length)',      unit: '%',          actual: -5.8 },
      { key: 'shrinkageWidth',    label: 'Shrinkage (Width)',       unit: '%',          actual: -4.2 },
      { key: 'colorFastnessWash', label: 'Color Fastness (Wash)',   unit: 'Grade 1-5',  actual: 3 },
      { key: 'colorFastnessRub',  label: 'Color Fastness (Rubbing)',unit: 'Grade 1-5',  actual: 2 },
      { key: 'pillingResistance', label: 'Pilling Resistance',      unit: 'Grade 1-5',  actual: 3 },
      { key: 'tensileStrength',   label: 'Tensile Strength',        unit: 'N',          standard: 180, actual: 165, result: 'Fail' },
    ],
    defects: [
      { rollNumber: 'R002', defectTypeId: null, defectTypeName: 'Weaving Defect', count: 3, remarks: 'Warp thread breakage — continuous' },
      { rollNumber: 'R002', defectTypeId: null, defectTypeName: 'Hole',           count: 2, remarks: 'Hole near center' },
      { rollNumber: 'R005', defectTypeId: null, defectTypeName: 'Stain',          count: 2, remarks: 'Oil stain — not washable' },
      { rollNumber: 'R005', defectTypeId: null, defectTypeName: 'Bowing',         count: 4, remarks: 'Significant bow — affects cutting' },
      { rollNumber: 'R007', defectTypeId: null, defectTypeName: 'Shade Bar',      count: 3, remarks: 'Visible shade variation' },
    ],
    overallResult: 'Fail',
    approver: 'Meena Sundaram',
    approverRole: 'Fabric Coordinator',
    approvalStatus: 'Rejected',
    approvalReason: null,
    rejectionReason: 'GSM out of range, excessive defects. Raising claim with supplier.',
    referBackReason: null,
  },
  {
    id: 6,
    qcNumber: 'FQC-2026-0006',
    version: 0,
    grnId: 4,
    grnNumber: 'GRN-F-2026-0004',
    poLineItemId: 2,
    fabricDescription: 'Viscose Rayon Twill',
    rollCount: 6,
    inspector: 'Deepa Krishnan',
    inspectionDate: '2026-03-16',
    // Legacy IN_PROGRESS → DRAFT (still editable)
    status: QC_STATUS.DRAFT,
    submittedAt: null,
    parameters: [
      { key: 'gsm',               label: 'GSM (Weight)',            unit: 'g/m²',       standard: 140, actual: 140.8, result: 'Pass' },
      { key: 'width',             label: 'Width',                   unit: 'inches',     standard: 54,  actual: 53.9,  result: 'Pass' },
      { key: 'shadeMatch',        label: 'Shade Variation',         unit: 'Grade 1-5',  actual: 4 },
      { key: 'shrinkageLength',   label: 'Shrinkage (Length)',      unit: '%',          actual: -3.0 },
      { key: 'shrinkageWidth',    label: 'Shrinkage (Width)',       unit: '%',          actual: -2.5 },
      { key: 'colorFastnessWash', label: 'Color Fastness (Wash)',   unit: 'Grade 1-5',  actual: 4 },
      { key: 'colorFastnessRub',  label: 'Color Fastness (Rubbing)',unit: 'Grade 1-5',  actual: 4 },
      { key: 'pillingResistance', label: 'Pilling Resistance',      unit: 'Grade 1-5',  actual: 3 },
      { key: 'tensileStrength',   label: 'Tensile Strength',        unit: 'N',          standard: 220, actual: 222, result: 'Pass' },
    ],
    defects: [],
    overallResult: 'Pending',
    approver: null,
    approverRole: 'Fabric Coordinator',
    approvalStatus: 'Pending',
    approvalReason: null,
    rejectionReason: null,
    referBackReason: null,
  },
  // ── New record: PENDING_APPROVAL — awaits approver action ──
  {
    id: 8,
    qcNumber: 'FQC-2026-0008',
    version: 0,
    grnId: 11,
    grnNumber: 'GRN/25-26/1011',
    poLineItemId: 5,
    fabricDescription: 'Black Denim 10oz Stretch',
    rollCount: 3,
    inspector: 'Sathish Babu',
    inspectionDate: '2026-04-08',
    status: QC_STATUS.PENDING_APPROVAL,
    submittedAt: '2026-04-08T14:20:00Z',
    parameters: [
      { key: 'gsm',               label: 'GSM (Weight)',            unit: 'g/m²',       standard: 340, actual: 341.2, result: 'Pass' },
      { key: 'width',             label: 'Width',                   unit: 'inches',     standard: 62,  actual: 62.0,  result: 'Pass' },
      { key: 'shadeMatch',        label: 'Shade Variation',         unit: 'Grade 1-5',  actual: 4 },
      { key: 'shrinkageLength',   label: 'Shrinkage (Length)',      unit: '%',          actual: -3.1 },
      { key: 'shrinkageWidth',    label: 'Shrinkage (Width)',       unit: '%',          actual: -2.3 },
      { key: 'colorFastnessWash', label: 'Color Fastness (Wash)',   unit: 'Grade 1-5',  actual: 4 },
      { key: 'colorFastnessRub',  label: 'Color Fastness (Rubbing)',unit: 'Grade 1-5',  actual: 3 },
      { key: 'pillingResistance', label: 'Pilling Resistance',      unit: 'Grade 1-5',  actual: 5 },
      { key: 'tensileStrength',   label: 'Tensile Strength',        unit: 'N',          standard: 450, actual: 452, result: 'Pass' },
    ],
    defects: [
      { rollNumber: 'S-011-001', defectTypeId: null, defectTypeName: 'Slub', count: 1, remarks: 'Minor slub near selvage' },
    ],
    overallResult: 'Pass',
    approver: null,
    approverRole: 'Fabric Coordinator',
    approvalStatus: 'Pending',
    approvalReason: null,
    rejectionReason: null,
    referBackReason: null,
  },
  // ── CONDITIONAL_PASS — approved with qualifications ──
  {
    id: 9,
    qcNumber: 'FQC-2026-0009',
    version: 0,
    grnId: 5,
    grnNumber: 'GRN-F-2026-0005',
    poLineItemId: 1,
    fabricDescription: 'Cotton Jersey 40s Reactive Black',
    rollCount: 4,
    inspector: 'Karthik Raman',
    inspectionDate: '2026-04-02',
    status: QC_STATUS.CONDITIONAL_PASS,
    submittedAt: '2026-04-02T10:45:00Z',
    parameters: [
      { key: 'gsm',               label: 'GSM (Weight)',            unit: 'g/m²',       standard: 160, actual: 167.8, result: 'Fail' },
      { key: 'width',             label: 'Width',                   unit: 'inches',     standard: 72,  actual: 71.5,  result: 'Pass' },
      { key: 'shadeMatch',        label: 'Shade Variation',         unit: 'Grade 1-5',  actual: 3 },
      { key: 'shrinkageLength',   label: 'Shrinkage (Length)',      unit: '%',          actual: -3.4 },
      { key: 'shrinkageWidth',    label: 'Shrinkage (Width)',       unit: '%',          actual: -2.9 },
      { key: 'colorFastnessWash', label: 'Color Fastness (Wash)',   unit: 'Grade 1-5',  actual: 4 },
      { key: 'colorFastnessRub',  label: 'Color Fastness (Rubbing)',unit: 'Grade 1-5',  actual: 3 },
      { key: 'pillingResistance', label: 'Pilling Resistance',      unit: 'Grade 1-5',  actual: 4 },
      { key: 'tensileStrength',   label: 'Tensile Strength',        unit: 'N',          standard: 280, actual: 278, result: 'Pass' },
    ],
    defects: [
      { rollNumber: 'CL001', defectTypeId: null, defectTypeName: 'Shade Bar', count: 2, remarks: 'Minor shade variation — acceptable for internal panels' },
    ],
    overallResult: 'Pass',
    approver: 'Meena Sundaram',
    approverRole: 'Fabric Coordinator',
    approvalStatus: 'Conditional Pass',
    approvalReason: 'GSM above tolerance but within acceptable range for this style. Released with caveat.',
    rejectionReason: null,
    referBackReason: null,
  },
];

// ─── MOCK ACCESSORIES QC (7 records — one per QC status) ───────────────────────
// Shape matches TrimsQCInspection's buildPayload output exactly:
//   { id, qcNumber, version, grnId, grnNumber, poLineItemId, inspectionDate,
//     inspector, status, submittedAt, qtyOrdered, qtyReceived, qtyChecked,
//     criteriaRows, overallResult, approver, approvalStatus,
//     approvalReason, rejectionReason, referBackReason }
// Every QC lifecycle status is represented so the list + view modal can be
// exercised end-to-end against mock data.
export const MOCK_TRIMS_QC = [
  {
    id: 1,
    qcNumber: 'AQC-2026-0001',
    version: 0,
    grnId: 101,
    grnNumber: 'GRN/25-26/2001',
    poLineItemId: 6,
    itemDescription: '4-Hole Smooth Button 15mm Natural',
    inspector: 'Vimal Raj',
    inspectionDate: '2026-03-09',
    status: QC_STATUS.APPROVED,
    submittedAt: '2026-03-09T11:00:00Z',
    qtyOrdered: 10000,
    qtyReceived: 10000,
    qtyChecked: 200,
    criteriaRows: [
      { id: 1, criteria: 'QTY', ok: true, notOk: false, remarks: '' },
      { id: 2, criteria: 'Colour', ok: true, notOk: false, remarks: '' },
      { id: 3, criteria: 'Quality', ok: true, notOk: false, remarks: '' },
      { id: 4, criteria: 'Pull Strength', ok: true, notOk: false, remarks: 'Met the benchmark' },
    ],
    overallResult: 'Pass',
    approver: 'Priya Sharma',
    approvalStatus: 'Approved',
    approvalReason: 'All criteria within tolerance. Cleared for production.',
    rejectionReason: null,
    referBackReason: null,
  },
  {
    id: 2,
    qcNumber: 'AQC-2026-0002',
    version: 0,
    grnId: 102,
    grnNumber: 'GRN/25-26/2002',
    poLineItemId: 7,
    itemDescription: 'YKK Invisible Zipper 18cm Black',
    inspector: 'Vimal Raj',
    inspectionDate: '2026-03-11',
    status: QC_STATUS.REJECTED,
    submittedAt: '2026-03-11T09:30:00Z',
    qtyOrdered: 8000,
    qtyReceived: 7800,
    qtyChecked: 200,
    criteriaRows: [
      { id: 1, criteria: 'QTY',           ok: false, notOk: true,  remarks: 'Short by 200 units vs PO' },
      { id: 2, criteria: 'Colour',        ok: true,  notOk: false, remarks: '' },
      { id: 4, criteria: 'Pull Strength', ok: false, notOk: true,  remarks: 'Multiple zippers failed tensile test' },
    ],
    overallResult: 'Fail',
    approver: 'Priya Sharma',
    approvalStatus: 'Rejected',
    approvalReason: null,
    rejectionReason: 'Shortfall + pull-strength failures. Raising claim with supplier.',
    referBackReason: null,
  },
  {
    id: 3,
    qcNumber: 'AQC-2026-0003',
    version: 0,
    grnId: 103,
    grnNumber: 'GRN/25-26/2003',
    poLineItemId: 8,
    itemDescription: 'Woven Main Label SS26',
    inspector: 'Anitha Mohan',
    inspectionDate: '2026-03-13',
    status: QC_STATUS.PENDING_APPROVAL,
    submittedAt: '2026-03-13T15:15:00Z',
    qtyOrdered: 20000,
    qtyReceived: 20000,
    qtyChecked: 500,
    criteriaRows: [
      { id: 1, criteria: 'QTY',           ok: true, notOk: false, remarks: '' },
      { id: 2, criteria: 'Colour',        ok: true, notOk: false, remarks: '' },
      { id: 5, criteria: 'Print Quality', ok: true, notOk: false, remarks: 'Minor smudges on 2 samples, within AQL' },
      { id: 7, criteria: 'Coding',        ok: true, notOk: false, remarks: '' },
    ],
    overallResult: 'Pass',
    approver: null,
    approvalStatus: 'Pending',
    approvalReason: null,
    rejectionReason: null,
    referBackReason: null,
  },
  {
    id: 4,
    qcNumber: 'AQC-2026-0004',
    version: 0,
    grnId: 104,
    grnNumber: 'GRN/25-26/2004',
    poLineItemId: 9,
    itemDescription: 'Polyester Sewing Thread 40/2',
    inspector: 'Vimal Raj',
    inspectionDate: '2026-03-15',
    // Previously approved, creator has requested refer-back for re-inspection.
    status: QC_STATUS.REFERRED_BACK_PENDING,
    submittedAt: '2026-03-15T10:45:00Z',
    qtyOrdered: 500,
    qtyReceived: 500,
    qtyChecked: 50,
    criteriaRows: [
      { id: 1, criteria: 'QTY',             ok: true, notOk: false, remarks: '' },
      { id: 4, criteria: 'Pull Strength',   ok: true, notOk: false, remarks: '' },
      { id: 6, criteria: 'Adhesion',        ok: true, notOk: false, remarks: '' },
    ],
    overallResult: 'Pass',
    approver: 'Priya Sharma',
    approvalStatus: 'Approved',
    approvalReason: 'All criteria met.',
    rejectionReason: null,
    referBackReason: 'New supplier lot received — re-inspect pull strength on a bigger sample.',
  },
  {
    id: 5,
    qcNumber: 'AQC-2026-0005',
    version: 0,
    grnId: 108,
    grnNumber: 'GRN/25-26/2008',
    poLineItemId: 10,
    itemDescription: 'Snap Buttons & Rivets Antique Brass',
    inspector: 'Anitha Mohan',
    inspectionDate: '2026-03-26',
    status: QC_STATUS.DRAFT,
    submittedAt: null,
    qtyOrdered: 5000,
    qtyReceived: 5000,
    qtyChecked: 125,
    criteriaRows: [
      { id: 1, criteria: 'QTY',             ok: false, notOk: false, remarks: '' },
      { id: 4, criteria: 'Pull Strength',   ok: false, notOk: false, remarks: '' },
      { id: 6, criteria: 'Adhesion',        ok: false, notOk: false, remarks: '' },
    ],
    overallResult: 'Pending',
    approver: null,
    approvalStatus: 'Pending',
    approvalReason: null,
    rejectionReason: null,
    referBackReason: null,
  },
  // ── New record: REFERRED_BACK — refer-back approved, editable again ──
  {
    id: 7,
    qcNumber: 'AQC-2026-0007',
    version: 0,
    grnId: 111,
    grnNumber: 'GRN/25-26/2011',
    poLineItemId: 8,
    itemDescription: 'Woven Main Label — H&M SS26',
    inspector: 'Anitha Mohan',
    inspectionDate: '2026-03-28',
    status: QC_STATUS.REFERRED_BACK,
    submittedAt: '2026-03-28T09:00:00Z',
    qtyOrdered: 20000,
    qtyReceived: 20000,
    qtyChecked: 500,
    criteriaRows: [
      { id: 1, criteria: 'QTY',           ok: true, notOk: false, remarks: '' },
      { id: 5, criteria: 'Print Quality', ok: true, notOk: false, remarks: '' },
      { id: 7, criteria: 'Coding',        ok: true, notOk: false, remarks: '' },
    ],
    overallResult: 'Pass',
    approver: 'Priya Sharma',
    approvalStatus: 'Approved',
    approvalReason: 'Initial approval granted.',
    rejectionReason: null,
    referBackReason: 'Refer-back approved — re-verify print alignment on a larger carton sample.',
  },
  // ── CONDITIONAL_PASS — approved with qualifications ──
  {
    id: 8,
    qcNumber: 'AQC-2026-0008',
    version: 0,
    grnId: 112,
    grnNumber: 'GRN/25-26/2012',
    poLineItemId: 9,
    itemDescription: 'Jacquard Elastic 38mm Black with Logo',
    inspector: 'Vimal Raj',
    inspectionDate: '2026-04-03',
    status: QC_STATUS.CONDITIONAL_PASS,
    submittedAt: '2026-04-03T15:10:00Z',
    qtyOrdered: 3000,
    qtyReceived: 3000,
    qtyChecked: 3000,
    qtyVerdict: 'MATCHED',
    criteriaRows: [
      { id: 1, criteria: 'QTY',           ok: true,  notOk: false, remarks: '' },
      { id: 2, criteria: 'Colour',        ok: false, notOk: true,  remarks: 'Logo shade slightly off standard — acceptable for secondary placement' },
      { id: 3, criteria: 'Quality',       ok: true,  notOk: false, remarks: '' },
    ],
    overallResult: 'Pass',
    approver: 'Priya Sharma',
    approvalStatus: 'Conditional Pass',
    approvalReason: 'Logo shade off standard but within tolerance. Released for use on internal waistbands only.',
    rejectionReason: null,
    referBackReason: null,
  },
];

// ─── MOCK FABRIC STOCK (20 records) ─────────────────────────────────────────────
export const MOCK_FABRIC_STOCK = [
  { id: 1, rollId: 101, rollNumber: 'R001', fabricDescription: 'Cotton Jersey 40s Reactive', materialCode: 'FAB-CJ40-WHT', composition: '100% Cotton', color: 'White', supplier: 'Fabric World Inc', grnNumber: 'GRN-F-2026-0001', style: 'AV-SS26-001', orderRef: 'ORD-2026-001', width: 72, weight: 68.5, gsm: 160, shadeLot: 'SL-A1', status: STOCK_STATUS.IN_STOCK, receivedDate: '2026-03-10', ageDays: 17, unitCost: 300.0, totalValue: 20550.0 },
  { id: 2, rollId: 102, rollNumber: 'R002', fabricDescription: 'Cotton Jersey 40s Reactive', materialCode: 'FAB-CJ40-WHT', composition: '100% Cotton', color: 'White', supplier: 'Fabric World Inc', grnNumber: 'GRN-F-2026-0001', style: 'AV-SS26-001', orderRef: 'ORD-2026-001', width: 72, weight: 71.2, gsm: 160, shadeLot: 'SL-A1', status: STOCK_STATUS.RESERVED, receivedDate: '2026-03-10', ageDays: 17, unitCost: 300.0, totalValue: 21360.0 },
  { id: 3, rollId: 103, rollNumber: 'R003', fabricDescription: 'Cotton Jersey 40s Reactive', materialCode: 'FAB-CJ40-WHT', composition: '100% Cotton', color: 'White', supplier: 'Fabric World Inc', grnNumber: 'GRN-F-2026-0001', style: 'AV-SS26-001', orderRef: 'ORD-2026-001', width: 72, weight: 69.8, gsm: 162, shadeLot: 'SL-A2', status: STOCK_STATUS.ISSUED, receivedDate: '2026-03-10', ageDays: 17, unitCost: 300.0, totalValue: 20940.0 },
  { id: 4, rollId: 104, rollNumber: 'R004', fabricDescription: 'Cotton Jersey 40s Reactive', materialCode: 'FAB-CJ40-WHT', composition: '100% Cotton', color: 'White', supplier: 'Fabric World Inc', grnNumber: 'GRN-F-2026-0001', style: 'AV-SS26-001', orderRef: 'ORD-2026-001', width: 72, weight: 70.0, gsm: 161, shadeLot: 'SL-A2', status: STOCK_STATUS.ISSUED, receivedDate: '2026-03-10', ageDays: 17, unitCost: 300.0, totalValue: 21000.0 },
  { id: 5, rollId: 201, rollNumber: 'R001', fabricDescription: '100% Polyester Satin 75D', materialCode: 'FAB-PS75-BLU', composition: '100% Polyester', color: 'Royal Blue', supplier: 'Tirupur Textiles Pvt Ltd', grnNumber: 'GRN-F-2026-0002', style: 'AV-SS26-005', orderRef: 'ORD-2026-005', width: 58, weight: 78.0, gsm: 95, shadeLot: 'SL-P1', status: STOCK_STATUS.IN_QC, receivedDate: '2026-03-12', ageDays: 15, unitCost: 320.0, totalValue: 24960.0 },
  { id: 6, rollId: 202, rollNumber: 'R002', fabricDescription: '100% Polyester Satin 75D', materialCode: 'FAB-PS75-BLU', composition: '100% Polyester', color: 'Royal Blue', supplier: 'Tirupur Textiles Pvt Ltd', grnNumber: 'GRN-F-2026-0002', style: 'AV-SS26-005', orderRef: 'ORD-2026-005', width: 58, weight: 77.5, gsm: 94, shadeLot: 'SL-P1', status: STOCK_STATUS.IN_QC, receivedDate: '2026-03-12', ageDays: 15, unitCost: 320.0, totalValue: 24800.0 },
  { id: 7, rollId: 301, rollNumber: 'R001', fabricDescription: 'CVC Pique 220 GSM', materialCode: 'FAB-CVCP-NVY', composition: '60% Cotton 40% Polyester', color: 'Navy', supplier: 'Vardhman Fabrics', grnNumber: 'GRN-F-2026-0003', style: 'AV-SS26-003', orderRef: 'ORD-2026-003', width: 66, weight: 75.0, gsm: 220, shadeLot: 'SL-CVC-01', status: STOCK_STATUS.IN_STOCK, receivedDate: '2026-03-14', ageDays: 13, unitCost: 350.0, totalValue: 26250.0 },
  { id: 8, rollId: 302, rollNumber: 'R002', fabricDescription: 'CVC Pique 220 GSM', materialCode: 'FAB-CVCP-NVY', composition: '60% Cotton 40% Polyester', color: 'Navy', supplier: 'Vardhman Fabrics', grnNumber: 'GRN-F-2026-0003', style: 'AV-SS26-003', orderRef: 'ORD-2026-003', width: 66, weight: 74.5, gsm: 219, shadeLot: 'SL-CVC-01', status: STOCK_STATUS.RESERVED, receivedDate: '2026-03-14', ageDays: 13, unitCost: 350.0, totalValue: 26075.0 },
  { id: 9, rollId: 303, rollNumber: 'R003', fabricDescription: 'CVC Pique 220 GSM', materialCode: 'FAB-CVCP-NVY', composition: '60% Cotton 40% Polyester', color: 'Navy', supplier: 'Vardhman Fabrics', grnNumber: 'GRN-F-2026-0003', style: 'AV-SS26-003', orderRef: 'ORD-2026-003', width: 66, weight: 76.2, gsm: 221, shadeLot: 'SL-CVC-01', status: STOCK_STATUS.IN_STOCK, receivedDate: '2026-03-14', ageDays: 13, unitCost: 350.0, totalValue: 26670.0 },
  { id: 10, rollId: 401, rollNumber: 'R001', fabricDescription: 'Viscose Rayon Twill', materialCode: 'FAB-VRT-BLK', composition: '100% Viscose', color: 'Black', supplier: 'Arvind Mills Ltd', grnNumber: 'GRN-F-2026-0004', style: 'AV-SS26-001', orderRef: 'ORD-2026-001', width: 54, weight: 85.0, gsm: 140, shadeLot: 'SL-VR-01', status: STOCK_STATUS.IN_STOCK, receivedDate: '2026-03-15', ageDays: 12, unitCost: 350.0, totalValue: 29750.0 },
  { id: 11, rollId: 402, rollNumber: 'R002', fabricDescription: 'Viscose Rayon Twill', materialCode: 'FAB-VRT-BLK', composition: '100% Viscose', color: 'Black', supplier: 'Arvind Mills Ltd', grnNumber: 'GRN-F-2026-0004', style: 'AV-SS26-001', orderRef: 'ORD-2026-001', width: 54, weight: 84.5, gsm: 139, shadeLot: 'SL-VR-01', status: STOCK_STATUS.ON_HOLD, receivedDate: '2026-03-15', ageDays: 12, unitCost: 350.0, totalValue: 29575.0 },
  { id: 12, rollId: 801, rollNumber: 'R001', fabricDescription: 'Indigo Denim 10oz Stretch', materialCode: 'FAB-DNM-IND', composition: '98% Cotton 2% Elastane', color: 'Indigo', supplier: 'Arvind Mills Ltd', grnNumber: 'GRN-F-2026-0008', style: 'AV-AW26-015', orderRef: 'ORD-2026-015', width: 62, weight: 90.0, gsm: 340, shadeLot: 'SL-DN-01', status: STOCK_STATUS.IN_STOCK, receivedDate: '2026-03-22', ageDays: 5, unitCost: 450.0, totalValue: 40500.0 },
  { id: 13, rollId: 802, rollNumber: 'R002', fabricDescription: 'Indigo Denim 10oz Stretch', materialCode: 'FAB-DNM-IND', composition: '98% Cotton 2% Elastane', color: 'Indigo', supplier: 'Arvind Mills Ltd', grnNumber: 'GRN-F-2026-0008', style: 'AV-AW26-015', orderRef: 'ORD-2026-015', width: 62, weight: 89.5, gsm: 338, shadeLot: 'SL-DN-01', status: STOCK_STATUS.IN_STOCK, receivedDate: '2026-03-22', ageDays: 5, unitCost: 450.0, totalValue: 40275.0 },
  { id: 14, rollId: 803, rollNumber: 'R003', fabricDescription: 'Indigo Denim 10oz Stretch', materialCode: 'FAB-DNM-IND', composition: '98% Cotton 2% Elastane', color: 'Indigo', supplier: 'Arvind Mills Ltd', grnNumber: 'GRN-F-2026-0008', style: 'AV-AW26-015', orderRef: 'ORD-2026-015', width: 62, weight: 91.0, gsm: 342, shadeLot: 'SL-DN-01', status: STOCK_STATUS.RESERVED, receivedDate: '2026-03-22', ageDays: 5, unitCost: 450.0, totalValue: 40950.0 },
  { id: 15, rollId: 901, rollNumber: 'R001', fabricDescription: 'Linen Cotton Blend 55/45', materialCode: 'FAB-LCB-ECR', composition: '55% Linen 45% Cotton', color: 'Ecru', supplier: 'Fabric World Inc', grnNumber: 'GRN-F-2026-0009', style: 'AV-SS26-012', orderRef: 'ORD-2026-012', width: 56, weight: 70.0, gsm: 150, shadeLot: 'SL-LC-01', status: STOCK_STATUS.DAMAGED, receivedDate: '2026-03-24', ageDays: 3, unitCost: 450.0, totalValue: 31500.0 },
  { id: 16, rollId: 902, rollNumber: 'R002', fabricDescription: 'Linen Cotton Blend 55/45', materialCode: 'FAB-LCB-ECR', composition: '55% Linen 45% Cotton', color: 'Ecru', supplier: 'Fabric World Inc', grnNumber: 'GRN-F-2026-0009', style: 'AV-SS26-012', orderRef: 'ORD-2026-012', width: 56, weight: 69.5, gsm: 149, shadeLot: 'SL-LC-01', status: STOCK_STATUS.DAMAGED, receivedDate: '2026-03-24', ageDays: 3, unitCost: 450.0, totalValue: 31275.0 },
  { id: 17, rollId: 304, rollNumber: 'R004', fabricDescription: 'CVC Pique 220 GSM', materialCode: 'FAB-CVCP-NVY', composition: '60% Cotton 40% Polyester', color: 'Navy', supplier: 'Vardhman Fabrics', grnNumber: 'GRN-F-2026-0003', style: 'AV-SS26-003', orderRef: 'ORD-2026-003', width: 66, weight: 75.8, gsm: 220, shadeLot: 'SL-CVC-02', status: STOCK_STATUS.IN_STOCK, receivedDate: '2026-03-14', ageDays: 13, unitCost: 350.0, totalValue: 26530.0 },
  { id: 18, rollId: 305, rollNumber: 'R005', fabricDescription: 'CVC Pique 220 GSM', materialCode: 'FAB-CVCP-NVY', composition: '60% Cotton 40% Polyester', color: 'Navy', supplier: 'Vardhman Fabrics', grnNumber: 'GRN-F-2026-0003', style: 'AV-SS26-003', orderRef: 'ORD-2026-003', width: 66, weight: 74.0, gsm: 218, shadeLot: 'SL-CVC-02', status: STOCK_STATUS.IN_STOCK, receivedDate: '2026-03-14', ageDays: 13, unitCost: 350.0, totalValue: 25900.0 },
  { id: 19, rollId: 804, rollNumber: 'R004', fabricDescription: 'Indigo Denim 10oz Stretch', materialCode: 'FAB-DNM-IND', composition: '98% Cotton 2% Elastane', color: 'Indigo', supplier: 'Arvind Mills Ltd', grnNumber: 'GRN-F-2026-0008', style: 'AV-AW26-015', orderRef: 'ORD-2026-015', width: 62, weight: 90.5, gsm: 340, shadeLot: 'SL-DN-02', status: STOCK_STATUS.IN_STOCK, receivedDate: '2026-03-22', ageDays: 5, unitCost: 450.0, totalValue: 40725.0 },
  { id: 20, rollId: 805, rollNumber: 'R005', fabricDescription: 'Indigo Denim 10oz Stretch', materialCode: 'FAB-DNM-IND', composition: '98% Cotton 2% Elastane', color: 'Indigo', supplier: 'Arvind Mills Ltd', grnNumber: 'GRN-F-2026-0008', style: 'AV-AW26-015', orderRef: 'ORD-2026-015', width: 62, weight: 89.0, gsm: 337, shadeLot: 'SL-DN-02', status: STOCK_STATUS.IN_STOCK, receivedDate: '2026-03-22', ageDays: 5, unitCost: 450.0, totalValue: 40050.0 },
];

// ─── MOCK ACCESSORIES STOCK (15 records) ────────────────────────────────────────
export const MOCK_ACCESSORIES_STOCK = [
  {
    id: 1, itemCode: 'BTN-4H-15MM-NAT', description: '4-Hole Smooth Button 15mm Natural', category: 'Buttons', uom: 'pcs', color: 'Natural', size: '15mm',
    style: 'AV-SS26-001', orderRef: 'ORD-2026-001', supplier: 'Button Bazaar', totalQty: 20000, available: 14500, reserved: 3500, issued: 2000, onHold: 0, reorderLevel: 5000, maxLevel: 25000, minLevel: 3000,
    lastReceived: '2026-03-08', unitCost: 1.5, sizeColorMatrix: { sizes: ['15mm'], colors: ['Natural', 'Black', 'Navy'], quantities: { 'Natural-15mm': 14500, 'Black-15mm': 11200, 'Navy-15mm': 9800 } },
  },
  {
    id: 2, itemCode: 'BTN-4H-15MM-BLK', description: '4-Hole Smooth Button 15mm Black', category: 'Buttons', uom: 'pcs', color: 'Black', size: '15mm',
    style: 'AV-SS26-001', orderRef: 'ORD-2026-001', supplier: 'Button Bazaar', totalQty: 15000, available: 11200, reserved: 2800, issued: 1000, onHold: 0, reorderLevel: 4000, maxLevel: 20000, minLevel: 2500,
    lastReceived: '2026-03-08', unitCost: 1.5, sizeColorMatrix: { sizes: ['15mm'], colors: ['Black'], quantities: { 'Black-15mm': 11200 } },
  },
  {
    id: 3, itemCode: 'ZIP-YKK-18CM-BLK', description: 'YKK Invisible Zipper 18cm Black', category: 'Zippers', uom: 'pcs', color: 'Black', size: '18cm',
    style: 'AV-SS26-008', orderRef: 'ORD-2026-008', supplier: 'Zipper King Exports', totalQty: 5000, available: 3200, reserved: 1200, issued: 600, onHold: 0, reorderLevel: 1500, maxLevel: 8000, minLevel: 1000,
    lastReceived: '2026-03-10', unitCost: 15.0, sizeColorMatrix: { sizes: ['18cm', '22cm'], colors: ['Black', 'Navy'], quantities: { 'Black-18cm': 3200, 'Navy-18cm': 2800, 'Black-22cm': 2100 } },
  },
  {
    id: 4, itemCode: 'ZIP-YKK-18CM-NVY', description: 'YKK Invisible Zipper 18cm Navy', category: 'Zippers', uom: 'pcs', color: 'Navy', size: '18cm',
    style: 'AV-SS26-008', orderRef: 'ORD-2026-008', supplier: 'Zipper King Exports', totalQty: 4000, available: 2800, reserved: 800, issued: 400, onHold: 0, reorderLevel: 1200, maxLevel: 6000, minLevel: 800,
    lastReceived: '2026-03-10', unitCost: 15.0, sizeColorMatrix: { sizes: ['18cm'], colors: ['Navy'], quantities: { 'Navy-18cm': 2800 } },
  },
  {
    id: 5, itemCode: 'LBL-WVN-MAIN-SS26', description: 'Woven Main Label SS26 Collection', category: 'Labels', uom: 'pcs', color: 'White/Black', size: '30x50mm',
    style: 'AV-SS26-001', orderRef: 'ORD-2026-001', supplier: 'Label Print Solutions', totalQty: 25000, available: 18000, reserved: 5000, issued: 2000, onHold: 0, reorderLevel: 8000, maxLevel: 30000, minLevel: 5000,
    lastReceived: '2026-03-12', unitCost: 0.8, sizeColorMatrix: { sizes: ['30x50mm'], colors: ['White/Black'], quantities: { 'White/Black-30x50mm': 18000 } },
  },
  {
    id: 6, itemCode: 'LBL-WVN-SIZE-M', description: 'Woven Size Label - M', category: 'Labels', uom: 'pcs', color: 'White/Black', size: '15x30mm',
    style: 'AV-SS26-001', orderRef: 'ORD-2026-001', supplier: 'Label Print Solutions', totalQty: 10000, available: 7500, reserved: 1500, issued: 1000, onHold: 0, reorderLevel: 3000, maxLevel: 15000, minLevel: 2000,
    lastReceived: '2026-03-12', unitCost: 0.5, sizeColorMatrix: { sizes: ['15x30mm'], colors: ['White/Black'], quantities: { 'White/Black-15x30mm': 7500 } },
  },
  {
    id: 7, itemCode: 'THR-POLY-40-WHT', description: 'Polyester Sewing Thread 40/2 White', category: 'Thread', uom: 'cones', color: 'White', size: '5000m',
    style: 'AV-SS26-001', orderRef: 'ORD-2026-001', supplier: 'Thread Masters Ltd', totalQty: 120, available: 85, reserved: 20, issued: 15, onHold: 0, reorderLevel: 30, maxLevel: 150, minLevel: 20,
    lastReceived: '2026-03-14', unitCost: 150.0, sizeColorMatrix: { sizes: ['5000m'], colors: ['White', 'Black', 'Navy'], quantities: { 'White-5000m': 85, 'Black-5000m': 78, 'Navy-5000m': 72 } },
  },
  {
    id: 8, itemCode: 'THR-POLY-40-BLK', description: 'Polyester Sewing Thread 40/2 Black', category: 'Thread', uom: 'cones', color: 'Black', size: '5000m',
    style: 'AV-SS26-008', orderRef: 'ORD-2026-008', supplier: 'Thread Masters Ltd', totalQty: 120, available: 78, reserved: 25, issued: 17, onHold: 0, reorderLevel: 30, maxLevel: 150, minLevel: 20,
    lastReceived: '2026-03-14', unitCost: 150.0, sizeColorMatrix: { sizes: ['5000m'], colors: ['Black'], quantities: { 'Black-5000m': 78 } },
  },
  {
    id: 9, itemCode: 'ELS-25MM-WHT', description: 'Knitted Elastic Band 25mm White', category: 'Elastic', uom: 'meters', color: 'White', size: '25mm',
    style: 'AV-SS26-003', orderRef: 'ORD-2026-003', supplier: 'Pacific Trims Co', totalQty: 2000, available: 1600, reserved: 300, issued: 100, onHold: 0, reorderLevel: 500, maxLevel: 3000, minLevel: 300,
    lastReceived: '2026-03-16', unitCost: 5.0, sizeColorMatrix: { sizes: ['25mm', '30mm'], colors: ['White', 'Black'], quantities: { 'White-25mm': 1600, 'Black-25mm': 1100, 'White-30mm': 1200 } },
  },
  {
    id: 10, itemCode: 'INT-FUS-WHT-40', description: 'Fusible Interlining Woven 40gsm White', category: 'Interlining', uom: 'meters', color: 'White', size: '150cm',
    style: 'AV-AW26-015', orderRef: 'ORD-2026-015', supplier: 'Pacific Trims Co', totalQty: 800, available: 650, reserved: 100, issued: 50, onHold: 0, reorderLevel: 200, maxLevel: 1000, minLevel: 150,
    lastReceived: '2026-03-19', unitCost: 35.0, sizeColorMatrix: { sizes: ['150cm'], colors: ['White', 'Black'], quantities: { 'White-150cm': 650, 'Black-150cm': 580 } },
  },
  {
    id: 11, itemCode: 'INT-FUS-BLK-40', description: 'Fusible Interlining Woven 40gsm Black', category: 'Interlining', uom: 'meters', color: 'Black', size: '150cm',
    style: 'AV-AW26-015', orderRef: 'ORD-2026-015', supplier: 'Pacific Trims Co', totalQty: 800, available: 580, reserved: 150, issued: 70, onHold: 0, reorderLevel: 200, maxLevel: 1000, minLevel: 150,
    lastReceived: '2026-03-19', unitCost: 35.0, sizeColorMatrix: { sizes: ['150cm'], colors: ['Black'], quantities: { 'Black-150cm': 580 } },
  },
  {
    id: 12, itemCode: 'LBL-CARE-POLY-STD', description: 'Printed Care Label Polyester Standard', category: 'Labels', uom: 'pcs', color: 'White/Black', size: '25x60mm',
    style: 'AV-SS26-001', orderRef: 'ORD-2026-001', supplier: 'Label Print Solutions', totalQty: 25000, available: 22000, reserved: 2000, issued: 1000, onHold: 0, reorderLevel: 8000, maxLevel: 30000, minLevel: 5000,
    lastReceived: '2026-03-21', unitCost: 0.6, sizeColorMatrix: { sizes: ['25x60mm'], colors: ['White/Black'], quantities: { 'White/Black-25x60mm': 22000 } },
  },
  {
    id: 13, itemCode: 'TAG-HANG-SS26', description: 'Hangtag SS26 Collection Recycled Card', category: 'Packaging', uom: 'pcs', color: 'Kraft', size: '50x80mm',
    style: 'AV-SS26-001', orderRef: 'ORD-2026-001', supplier: 'Label Print Solutions', totalQty: 15000, available: 13500, reserved: 1000, issued: 500, onHold: 0, reorderLevel: 5000, maxLevel: 20000, minLevel: 3000,
    lastReceived: '2026-03-21', unitCost: 2.5, sizeColorMatrix: { sizes: ['50x80mm'], colors: ['Kraft'], quantities: { 'Kraft-50x80mm': 13500 } },
  },
  {
    id: 14, itemCode: 'BTN-SNAP-15MM-ANT', description: 'Snap Button 15mm Antique Brass', category: 'Buttons', uom: 'pcs', color: 'Antique Brass', size: '15mm',
    style: 'AV-AW26-015', orderRef: 'ORD-2026-015', supplier: 'Button Bazaar', totalQty: 5000, available: 4500, reserved: 500, issued: 0, onHold: 0, reorderLevel: 1500, maxLevel: 8000, minLevel: 1000,
    lastReceived: '2026-03-25', unitCost: 5.0, sizeColorMatrix: { sizes: ['15mm'], colors: ['Antique Brass'], quantities: { 'Antique Brass-15mm': 4500 } },
  },
  {
    id: 15, itemCode: 'RVT-6MM-ANT', description: 'Rivet 6mm Antique Brass', category: 'Buttons', uom: 'pcs', color: 'Antique Brass', size: '6mm',
    style: 'AV-AW26-015', orderRef: 'ORD-2026-015', supplier: 'Button Bazaar', totalQty: 3000, available: 2800, reserved: 200, issued: 0, onHold: 0, reorderLevel: 800, maxLevel: 5000, minLevel: 500,
    lastReceived: '2026-03-25', unitCost: 3.0, sizeColorMatrix: { sizes: ['6mm'], colors: ['Antique Brass'], quantities: { 'Antique Brass-6mm': 2800 } },
  },
];

// ─── MOCK FABRIC ISSUES (5 records) ─────────────────────────────────────────────
export const MOCK_FABRIC_ISSUES = [
  {
    id: 1,
    issueNumber: 'FIS-2026-0001',
    productionOrder: 'PRD-2026-001',
    style: 'AV-SS26-001',
    issueDate: '2026-03-18',
    issuedBy: 'Ranjith Kumar',
    receivedBy: 'Mohan Babu',
    productionLine: 'Cutting Line 1',
    status: ISSUE_STATUS.ISSUED,
    fabricDescription: 'Cotton Jersey 40s Reactive',
    rolls: [
      { rollId: 103, rollNumber: 'R003', issuedWeight: 69.8, shadeLot: 'SL-A2' },
      { rollId: 104, rollNumber: 'R004', issuedWeight: 70.0, shadeLot: 'SL-A2' },
    ],
    totalWeight: 139.8,
    bomRequired: 135.0,
    variance: 4.8,
    variancePct: 3.56,
    remarks: 'Extra 3.5% issued for cutting wastage allowance',
  },
  {
    id: 2,
    issueNumber: 'FIS-2026-0002',
    productionOrder: 'PRD-2026-002',
    style: 'AV-SS26-003',
    issueDate: '2026-03-20',
    issuedBy: 'Sathish Babu',
    receivedBy: 'Vijay Kumar',
    productionLine: 'Cutting Line 2',
    status: ISSUE_STATUS.ISSUED,
    fabricDescription: 'CVC Pique 220 GSM',
    rolls: [
      { rollId: 307, rollNumber: 'R007', issuedWeight: 75.0, shadeLot: 'SL-CVC-01' },
      { rollId: 308, rollNumber: 'R008', issuedWeight: 74.8, shadeLot: 'SL-CVC-02' },
      { rollId: 309, rollNumber: 'R009', issuedWeight: 75.5, shadeLot: 'SL-CVC-02' },
    ],
    totalWeight: 225.3,
    bomRequired: 220.0,
    variance: 5.3,
    variancePct: 2.41,
    remarks: 'Polo shirt production — shade grouped for marker planning',
  },
  {
    id: 3,
    issueNumber: 'FIS-2026-0003',
    productionOrder: 'PRD-2026-003',
    style: 'AV-AW26-015',
    issueDate: '2026-03-24',
    issuedBy: 'Ranjith Kumar',
    receivedBy: 'Mohan Babu',
    productionLine: 'Cutting Line 1',
    status: ISSUE_STATUS.PARTIAL,
    fabricDescription: 'Indigo Denim 10oz Stretch',
    rolls: [
      { rollId: 801, rollNumber: 'R001', issuedWeight: 90.0, shadeLot: 'SL-DN-01' },
      { rollId: 802, rollNumber: 'R002', issuedWeight: 89.5, shadeLot: 'SL-DN-01' },
    ],
    totalWeight: 179.5,
    bomRequired: 360.0,
    variance: -180.5,
    variancePct: -50.14,
    remarks: 'First batch issue — remaining rolls after QC clearance',
  },
  {
    id: 4,
    issueNumber: 'FIS-2026-0004',
    productionOrder: 'PRD-2026-001',
    style: 'AV-SS26-001',
    issueDate: '2026-03-25',
    issuedBy: 'Sathish Babu',
    receivedBy: 'Vijay Kumar',
    productionLine: 'Cutting Line 2',
    status: ISSUE_STATUS.DRAFT,
    fabricDescription: 'Cotton Jersey 40s Reactive',
    rolls: [
      { rollId: 105, rollNumber: 'R005', issuedWeight: 72.3, shadeLot: 'SL-A1' },
      { rollId: 106, rollNumber: 'R006', issuedWeight: 67.9, shadeLot: 'SL-A1' },
    ],
    totalWeight: 140.2,
    bomRequired: 135.0,
    variance: 5.2,
    variancePct: 3.85,
    remarks: 'Second batch for T-shirt order — same shade lot grouped',
  },
  {
    id: 5,
    issueNumber: 'FIS-2026-0005',
    productionOrder: 'PRD-2026-004',
    style: 'AV-SS26-008',
    issueDate: '2026-03-26',
    issuedBy: 'Ranjith Kumar',
    receivedBy: 'Mohan Babu',
    productionLine: 'Cutting Line 1',
    status: ISSUE_STATUS.CLOSED,
    fabricDescription: 'Viscose Rayon Twill',
    rolls: [
      { rollId: 401, rollNumber: 'R001', issuedWeight: 85.0, shadeLot: 'SL-VR-01' },
      { rollId: 403, rollNumber: 'R003', issuedWeight: 86.0, shadeLot: 'SL-VR-01' },
    ],
    totalWeight: 171.0,
    bomRequired: 168.0,
    variance: 3.0,
    variancePct: 1.79,
    remarks: 'Blouse production completed — all fabric utilized',
  },
];

// ─── MOCK ACCESSORIES ISSUES (5 records) ────────────────────────────────────────
export const MOCK_ACCESSORIES_ISSUES = [
  {
    id: 1,
    issueNumber: 'AIS-2026-0001',
    productionOrder: 'PRD-2026-001',
    style: 'AV-SS26-001',
    issueDate: '2026-03-19',
    issuedBy: 'Priya Sharma',
    receivedBy: 'Kala Devi',
    status: ISSUE_STATUS.ISSUED,
    items: [
      { itemCode: 'BTN-4H-15MM-NAT', description: '4-Hole Smooth Button 15mm Natural', color: 'Natural', size: '15mm', bomQty: 3500, issuedQty: 3500, uom: 'pcs' },
      { itemCode: 'LBL-WVN-MAIN-SS26', description: 'Woven Main Label SS26 Collection', color: 'White/Black', size: '30x50mm', bomQty: 2000, issuedQty: 2000, uom: 'pcs' },
      { itemCode: 'LBL-CARE-POLY-STD', description: 'Printed Care Label Polyester Standard', color: 'White/Black', size: '25x60mm', bomQty: 2000, issuedQty: 2000, uom: 'pcs' },
      { itemCode: 'THR-POLY-40-WHT', description: 'Polyester Sewing Thread 40/2 White', color: 'White', size: '5000m', bomQty: 15, issuedQty: 15, uom: 'cones' },
    ],
    totalItems: 7515,
    remarks: 'Full kit issue for T-shirt order AV-SS26-001',
  },
  {
    id: 2,
    issueNumber: 'AIS-2026-0002',
    productionOrder: 'PRD-2026-002',
    style: 'AV-SS26-003',
    issueDate: '2026-03-21',
    issuedBy: 'Priya Sharma',
    receivedBy: 'Sundar Raj',
    status: ISSUE_STATUS.ISSUED,
    items: [
      { itemCode: 'BTN-4H-15MM-NVY', description: '4-Hole Smooth Button 15mm Navy', color: 'Navy', size: '15mm', bomQty: 2800, issuedQty: 2800, uom: 'pcs' },
      { itemCode: 'LBL-WVN-MAIN-SS26', description: 'Woven Main Label SS26 Collection', color: 'White/Black', size: '30x50mm', bomQty: 1500, issuedQty: 1500, uom: 'pcs' },
      { itemCode: 'THR-POLY-40-NVY', description: 'Polyester Sewing Thread 40/2 Navy', color: 'Navy', size: '5000m', bomQty: 12, issuedQty: 12, uom: 'cones' },
    ],
    totalItems: 4312,
    remarks: 'Polo shirt trims — navy color way',
  },
  {
    id: 3,
    issueNumber: 'AIS-2026-0003',
    productionOrder: 'PRD-2026-003',
    style: 'AV-AW26-015',
    issueDate: '2026-03-25',
    issuedBy: 'Priya Sharma',
    receivedBy: 'Kala Devi',
    status: ISSUE_STATUS.PARTIAL,
    items: [
      { itemCode: 'BTN-SNAP-15MM-ANT', description: 'Snap Button 15mm Antique Brass', color: 'Antique Brass', size: '15mm', bomQty: 2500, issuedQty: 500, uom: 'pcs' },
      { itemCode: 'RVT-6MM-ANT', description: 'Rivet 6mm Antique Brass', color: 'Antique Brass', size: '6mm', bomQty: 1200, issuedQty: 200, uom: 'pcs' },
      { itemCode: 'ZIP-YKK-22CM-BLK', description: 'YKK Open-End Zipper 22cm Black', color: 'Black', size: '22cm', bomQty: 600, issuedQty: 600, uom: 'pcs' },
      { itemCode: 'INT-FUS-BLK-40', description: 'Fusible Interlining Woven 40gsm Black', color: 'Black', size: '150cm', bomQty: 150, issuedQty: 150, uom: 'meters' },
    ],
    totalItems: 1450,
    remarks: 'Partial issue for denim jacket — snap buttons pending QC',
  },
  {
    id: 4,
    issueNumber: 'AIS-2026-0004',
    productionOrder: 'PRD-2026-004',
    style: 'AV-SS26-008',
    issueDate: '2026-03-26',
    issuedBy: 'Sathish Babu',
    receivedBy: 'Sundar Raj',
    status: ISSUE_STATUS.DRAFT,
    items: [
      { itemCode: 'ZIP-YKK-18CM-BLK', description: 'YKK Invisible Zipper 18cm Black', color: 'Black', size: '18cm', bomQty: 800, issuedQty: 800, uom: 'pcs' },
      { itemCode: 'LBL-WVN-MAIN-SS26', description: 'Woven Main Label SS26 Collection', color: 'White/Black', size: '30x50mm', bomQty: 1000, issuedQty: 1000, uom: 'pcs' },
      { itemCode: 'THR-POLY-40-BLK', description: 'Polyester Sewing Thread 40/2 Black', color: 'Black', size: '5000m', bomQty: 10, issuedQty: 10, uom: 'cones' },
    ],
    totalItems: 1810,
    remarks: 'Blouse trims issue — awaiting approval',
  },
  {
    id: 5,
    issueNumber: 'AIS-2026-0005',
    productionOrder: 'PRD-2026-001',
    style: 'AV-SS26-001',
    issueDate: '2026-03-27',
    issuedBy: 'Priya Sharma',
    receivedBy: 'Kala Devi',
    status: ISSUE_STATUS.RETURNED,
    items: [
      { itemCode: 'BTN-4H-15MM-NAT', description: '4-Hole Smooth Button 15mm Natural', color: 'Natural', size: '15mm', bomQty: 0, issuedQty: 150, uom: 'pcs' },
      { itemCode: 'THR-POLY-40-WHT', description: 'Polyester Sewing Thread 40/2 White', color: 'White', size: '5000m', bomQty: 0, issuedQty: 2, uom: 'cones' },
    ],
    totalItems: 152,
    remarks: 'Excess trims returned after production completion',
  },
];

// ─── MOCK ADJUSTMENTS (4 records) ───────────────────────────────────────────────
export const MOCK_ADJUSTMENTS = [
  {
    id: 1,
    adjustmentNumber: 'ADJ-2026-0001',
    adjustmentDate: '2026-03-20',
    type: 'Fabric',
    reason: 'Physical stock count — quarterly audit',
    countedBy: 'Ranjith Kumar',
    status: ADJUSTMENT_STATUS.APPROVED,
    items: [
      { itemId: 1, description: 'Cotton Jersey 40s Reactive (Roll R001)', systemQty: 68.5, physicalCount: 68.2, variance: -0.3, variancePct: -0.44, uom: 'kg' },
      { itemId: 7, description: 'CVC Pique 220 GSM (Roll R001)', systemQty: 75.0, physicalCount: 74.8, variance: -0.2, variancePct: -0.27, uom: 'kg' },
      { itemId: 10, description: 'Viscose Rayon Twill (Roll R001)', systemQty: 85.0, physicalCount: 85.0, variance: 0.0, variancePct: 0.0, uom: 'kg' },
    ],
    totalVarianceValue: -175.0,
    approver: 'Meena Sundaram',
    approvalRemarks: 'Minor variance within tolerance. Approved.',
  },
  {
    id: 2,
    adjustmentNumber: 'ADJ-2026-0002',
    adjustmentDate: '2026-03-22',
    type: 'Accessories',
    reason: 'Damaged goods write-off — water damage in store',
    countedBy: 'Priya Sharma',
    status: ADJUSTMENT_STATUS.APPROVED,
    items: [
      { itemId: 5, description: 'Woven Main Label SS26 Collection', systemQty: 18500, physicalCount: 18000, variance: -500, variancePct: -2.7, uom: 'pcs' },
      { itemId: 12, description: 'Printed Care Label Polyester Standard', systemQty: 23000, physicalCount: 22000, variance: -1000, variancePct: -4.35, uom: 'pcs' },
    ],
    totalVarianceValue: -1000.0,
    approver: 'Ranjith Kumar',
    approvalRemarks: 'Water damage confirmed by store supervisor. Write-off approved.',
  },
  {
    id: 3,
    adjustmentNumber: 'ADJ-2026-0003',
    adjustmentDate: '2026-03-25',
    type: 'Accessories',
    reason: 'Cycle count discrepancy — thread inventory',
    countedBy: 'Sathish Babu',
    status: ADJUSTMENT_STATUS.PENDING_APPROVAL,
    items: [
      { itemId: 7, description: 'Polyester Sewing Thread 40/2 White', systemQty: 87, physicalCount: 85, variance: -2, variancePct: -2.3, uom: 'cones' },
      { itemId: 8, description: 'Polyester Sewing Thread 40/2 Black', systemQty: 80, physicalCount: 78, variance: -2, variancePct: -2.5, uom: 'cones' },
    ],
    totalVarianceValue: -600.0,
    approver: null,
    approvalRemarks: null,
  },
  {
    id: 4,
    adjustmentNumber: 'ADJ-2026-0004',
    adjustmentDate: '2026-03-26',
    type: 'Fabric',
    reason: 'Returned fabric from production — excess cut pieces',
    countedBy: 'Mohan Babu',
    status: ADJUSTMENT_STATUS.DRAFT,
    items: [
      { itemId: 3, description: 'Cotton Jersey 40s Reactive (Roll R003 remnant)', systemQty: 0, physicalCount: 8.5, variance: 8.5, variancePct: 100.0, uom: 'kg' },
      { itemId: 4, description: 'Cotton Jersey 40s Reactive (Roll R004 remnant)', systemQty: 0, physicalCount: 5.2, variance: 5.2, variancePct: 100.0, uom: 'kg' },
    ],
    totalVarianceValue: 4110.0,
    approver: null,
    approvalRemarks: null,
  },
];

// ─── MOCK PURCHASE ORDERS FOR GRN (6 records) ──────────────────────────────────
export const MOCK_PURCHASE_ORDERS_FOR_GRN = [
  {
    id: 111,
    poNumber: 'PO-FAB-2026-0111',
    supplier: 'Fabric World Inc',
    buyerName: 'Nordstrom Inc',
    styleNumber: 'AV-SS26-001',
    poDate: '2026-03-20',
    createdDate: '2026-03-15',
    expectedDeliveryDate: '2026-04-30',
    status: 'Sent_To_Supplier',
    items: [
      { id: 1, itemCode: 'FAB-CJ40-BLK', description: 'Cotton Jersey 40s Reactive Black', category: 'Fabric', variantId: 'V-FAB-CJ40-BLK', uom: 'kg', orderedQty: 600, receivedQty: 0, pendingQty: 600, rate: 300.0 },
      { id: 2, itemCode: 'FAB-CJ40-GRY', description: 'Cotton Jersey 40s Reactive Heather Grey', category: 'Fabric', variantId: 'V-FAB-CJ40-GRY', uom: 'kg', orderedQty: 400, receivedQty: 0, pendingQty: 400, rate: 310.0 },
    ],
  },
  {
    id: 112,
    poNumber: 'PO-FAB-2026-0112',
    supplier: 'Vardhman Fabrics',
    buyerName: 'H&M Group',
    styleNumber: 'AV-SS26-005',
    poDate: '2026-03-22',
    createdDate: '2026-03-18',
    expectedDeliveryDate: '2026-05-05',
    status: 'Sent_To_Supplier',
    items: [
      { id: 3, itemCode: 'FAB-CVCP-OLV', description: 'CVC Pique 220 GSM Olive', category: 'Fabric', variantId: 'V-FAB-CVCP-OLV', uom: 'kg', orderedQty: 800, receivedQty: 0, pendingQty: 800, rate: 350.0 },
    ],
  },
  {
    id: 113,
    poNumber: 'PO-FAB-2026-0113',
    supplier: 'Arvind Mills Ltd',
    buyerName: 'Marks & Spencer',
    styleNumber: 'AV-AW26-015',
    poDate: '2026-03-23',
    createdDate: '2026-03-19',
    expectedDeliveryDate: '2026-05-10',
    status: 'Sent_To_Supplier',
    items: [
      { id: 4, itemCode: 'FAB-DNM-LBL', description: 'Light Blue Denim 8oz', category: 'Fabric', variantId: 'V-FAB-DNM-LBL', uom: 'kg', orderedQty: 500, receivedQty: 0, pendingQty: 500, rate: 420.0 },
      { id: 5, itemCode: 'FAB-DNM-BLK', description: 'Black Denim 10oz Stretch', category: 'Fabric', variantId: 'V-FAB-DNM-BLK', uom: 'kg', orderedQty: 450, receivedQty: 0, pendingQty: 450, rate: 450.0 },
    ],
  },
  {
    id: 214,
    poNumber: 'PO-ACC-2026-0209',
    supplier: 'Button Bazaar',
    buyerName: 'Nordstrom Inc',
    styleNumber: 'AV-AW26-015',
    poDate: '2026-03-24',
    createdDate: '2026-03-20',
    expectedDeliveryDate: '2026-05-12',
    status: 'Sent_To_Supplier',
    items: [
      { id: 6, itemCode: 'BTN-4H-20MM-BRN', description: '4-Hole Horn Button 20mm Brown', category: 'Trims', variantId: 'V-BTN-4H-20MM-BRN', uom: 'pcs', orderedQty: 10000, receivedQty: 0, pendingQty: 10000, rate: 3.5 },
      { id: 7, itemCode: 'BTN-SHANK-15MM-GLD', description: 'Shank Button 15mm Gold', category: 'Trims', variantId: 'V-BTN-SHANK-15MM-GLD', uom: 'pcs', orderedQty: 5000, receivedQty: 0, pendingQty: 5000, rate: 4.0 },
    ],
  },
  {
    id: 215,
    poNumber: 'PO-ACC-2026-0210',
    supplier: 'Zipper King Exports',
    buyerName: 'H&M Group',
    styleNumber: 'AV-AW26-015',
    poDate: '2026-03-25',
    createdDate: '2026-03-20',
    expectedDeliveryDate: '2026-05-13',
    status: 'Sent_To_Supplier',
    items: [
      { id: 8, itemCode: 'ZIP-YKK-50CM-BLK', description: 'YKK Metal Zipper 50cm Black/Antique', category: 'Trims', variantId: 'V-ZIP-YKK-50CM-BLK', uom: 'pcs', orderedQty: 2000, receivedQty: 0, pendingQty: 2000, rate: 25.0 },
    ],
  },
  {
    id: 216,
    poNumber: 'PO-ACC-2026-0211',
    supplier: 'Pacific Trims Co',
    buyerName: 'Marks & Spencer',
    styleNumber: 'AV-SS26-008',
    poDate: '2026-03-26',
    createdDate: '2026-03-21',
    expectedDeliveryDate: '2026-05-14',
    status: 'Sent_To_Supplier',
    items: [
      { id: 9, itemCode: 'ELS-38MM-BLK-LOGO', description: 'Jacquard Elastic 38mm Black with Logo', category: 'Trims', variantId: 'V-ELS-38MM-BLK-LOGO', uom: 'meters', orderedQty: 3000, receivedQty: 0, pendingQty: 3000, rate: 12.0 },
      { id: 10, itemCode: 'DRW-CORD-5MM-BLK', description: 'Drawcord Round 5mm Black', category: 'Trims', variantId: 'V-DRW-CORD-5MM-BLK', uom: 'meters', orderedQty: 2000, receivedQty: 0, pendingQty: 2000, rate: 4.0 },
    ],
  },
];

// ─── MOCK ITEM VARIANTS LOOKUP (variantId → item master attrs) ────────────────
export const MOCK_ITEM_VARIANTS = {
  'V-FAB-CJ40-BLK':       { itemCode: 'FAB-CJ40-BLK', itemName: 'Cotton Jersey 40s Reactive Black', color: 'Black', size: '-', primaryUom: 'kg', secondaryUom: 'mtrs', category: 'Fabric', attributes: { width: 72, gsm: 160 } },
  'V-FAB-CJ40-GRY':       { itemCode: 'FAB-CJ40-GRY', itemName: 'Cotton Jersey 40s Reactive Heather Grey', color: 'Heather Grey', size: '-', primaryUom: 'kg', secondaryUom: 'mtrs', category: 'Fabric', attributes: { width: 72, gsm: 160 } },
  'V-FAB-CVCP-OLV':       { itemCode: 'FAB-CVCP-OLV', itemName: 'CVC Pique 220 GSM Olive', color: 'Olive', size: '-', primaryUom: 'kg', secondaryUom: 'mtrs', category: 'Fabric', attributes: { width: 66, gsm: 220 } },
  'V-FAB-DNM-LBL':        { itemCode: 'FAB-DNM-LBL', itemName: 'Light Blue Denim 8oz', color: 'Light Blue', size: '-', primaryUom: 'kg', secondaryUom: 'mtrs', category: 'Fabric', attributes: { width: 60, gsm: 270 } },
  'V-FAB-DNM-BLK':        { itemCode: 'FAB-DNM-BLK', itemName: 'Black Denim 10oz Stretch', color: 'Black', size: '-', primaryUom: 'kg', secondaryUom: 'mtrs', category: 'Fabric', attributes: { width: 62, gsm: 340 } },
  'V-BTN-4H-20MM-BRN':    { itemCode: 'BTN-4H-20MM-BRN', itemName: '4-Hole Horn Button 20mm Brown', color: 'Brown', size: '20mm', primaryUom: 'pcs', secondaryUom: 'gross', category: 'Trims', attributes: {} },
  'V-BTN-SHANK-15MM-GLD': { itemCode: 'BTN-SHANK-15MM-GLD', itemName: 'Shank Button 15mm Gold', color: 'Gold', size: '15mm', primaryUom: 'pcs', secondaryUom: 'gross', category: 'Trims', attributes: {} },
  'V-ZIP-YKK-50CM-BLK':   { itemCode: 'ZIP-YKK-50CM-BLK', itemName: 'YKK Metal Zipper 50cm Black', color: 'Black', size: '50cm', primaryUom: 'pcs', secondaryUom: 'dozen', category: 'Trims', attributes: {} },
  'V-ELS-38MM-BLK-LOGO':  { itemCode: 'ELS-38MM-BLK-LOGO', itemName: 'Jacquard Elastic 38mm Black with Logo', color: 'Black', size: '38mm', primaryUom: 'meters', secondaryUom: 'rolls', category: 'Trims', attributes: {} },
  'V-DRW-CORD-5MM-BLK':   { itemCode: 'DRW-CORD-5MM-BLK', itemName: 'Drawcord Round 5mm Black', color: 'Black', size: '5mm', primaryUom: 'meters', secondaryUom: 'rolls', category: 'Trims', attributes: {} },
};

// ─── MOCK DEFECT TYPES (master) ────────────────────────────────────────────────
export const MOCK_DEFECT_TYPES = [
  { id: 1, name: 'Hole', description: 'Hole or tear in the fabric', active: true },
  { id: 2, name: 'Stain', description: 'Stain, dye marks or oil spots', active: true },
  { id: 3, name: 'Shade Bar', description: 'Visible shade variation across the width', active: true },
  { id: 4, name: 'Broken End', description: 'Broken warp end or thread', active: true },
  { id: 5, name: 'Missing Pick', description: 'Missing weft pick', active: true },
  { id: 6, name: 'Slub', description: 'Thick or thin yarn slubs', active: true },
  { id: 7, name: 'Oil Spot', description: 'Oil contamination on fabric surface', active: true },
  { id: 8, name: 'Crease Mark', description: 'Crease mark from improper handling', active: true },
  { id: 9, name: 'Bowing', description: 'Bowing or skew distortion', active: true },
  { id: 10, name: 'Selvage Defect', description: 'Loose, tight or damaged selvage', active: true },
  { id: 11, name: 'Weaving Defect', description: 'Other weaving-related defects', active: true },
];

// ─── MOCK TRIMS QC CRITERIA (master) ───────────────────────────────────────────
export const MOCK_TRIMS_QC_CRITERIA = [
  { id: 1, name: 'QTY', description: 'Quantity matches DC and PO', active: true },
  { id: 2, name: 'Colour', description: 'Colour matches approved sample', active: true },
  { id: 3, name: 'Quality', description: 'Overall quality acceptable', active: true },
  { id: 4, name: 'Pull Strength', description: 'Tensile / pull-test strength meets standard', active: true },
  { id: 5, name: 'Print Quality', description: 'Print clarity, alignment, finish', active: true },
  { id: 6, name: 'Adhesion', description: 'Adhesive bonding holds under stress', active: true },
  { id: 7, name: 'Coding', description: 'Bar/QR/article codes correct and scannable', active: true },
];

// ─── MOCK PRODUCTION ORDERS (4 records) ─────────────────────────────────────────
export const MOCK_PRODUCTION_ORDERS = [
  {
    id: 1,
    poNumber: 'PRD-2026-001',
    style: 'AV-SS26-001',
    buyer: 'Nordstrom Inc',
    orderQty: 5000,
    status: 'In Progress',
    bom: [
      { itemCode: 'FAB-CJ40-WHT', description: 'Cotton Jersey 40s Reactive White', requiredQty: 675.0, issuedQty: 280.0, uom: 'kg' },
      { itemCode: 'BTN-4H-15MM-NAT', description: '4-Hole Smooth Button 15mm Natural', requiredQty: 5000, issuedQty: 3350, uom: 'pcs' },
      { itemCode: 'LBL-WVN-MAIN-SS26', description: 'Woven Main Label SS26 Collection', requiredQty: 5000, issuedQty: 2000, uom: 'pcs' },
      { itemCode: 'LBL-CARE-POLY-STD', description: 'Printed Care Label Polyester Standard', requiredQty: 5000, issuedQty: 2000, uom: 'pcs' },
      { itemCode: 'THR-POLY-40-WHT', description: 'Polyester Sewing Thread 40/2 White', requiredQty: 35, issuedQty: 13, uom: 'cones' },
      { itemCode: 'TAG-HANG-SS26', description: 'Hangtag SS26 Collection Recycled Card', requiredQty: 5000, issuedQty: 500, uom: 'pcs' },
    ],
  },
  {
    id: 2,
    poNumber: 'PRD-2026-002',
    style: 'AV-SS26-003',
    buyer: 'H&M Group',
    orderQty: 3000,
    status: 'In Progress',
    bom: [
      { itemCode: 'FAB-CVCP-NVY', description: 'CVC Pique 220 GSM Navy', requiredQty: 450.0, issuedQty: 225.3, uom: 'kg' },
      { itemCode: 'BTN-4H-15MM-NVY', description: '4-Hole Smooth Button 15mm Navy', requiredQty: 3000, issuedQty: 2800, uom: 'pcs' },
      { itemCode: 'LBL-WVN-MAIN-SS26', description: 'Woven Main Label SS26 Collection', requiredQty: 3000, issuedQty: 1500, uom: 'pcs' },
      { itemCode: 'THR-POLY-40-NVY', description: 'Polyester Sewing Thread 40/2 Navy', requiredQty: 22, issuedQty: 12, uom: 'cones' },
    ],
  },
  {
    id: 3,
    poNumber: 'PRD-2026-003',
    style: 'AV-AW26-015',
    buyer: 'Zara International',
    orderQty: 2000,
    status: 'Cutting',
    bom: [
      { itemCode: 'FAB-DNM-IND', description: 'Indigo Denim 10oz Stretch', requiredQty: 720.0, issuedQty: 179.5, uom: 'kg' },
      { itemCode: 'BTN-SNAP-15MM-ANT', description: 'Snap Button 15mm Antique Brass', requiredQty: 5000, issuedQty: 500, uom: 'pcs' },
      { itemCode: 'RVT-6MM-ANT', description: 'Rivet 6mm Antique Brass', requiredQty: 2400, issuedQty: 200, uom: 'pcs' },
      { itemCode: 'ZIP-YKK-22CM-BLK', description: 'YKK Open-End Zipper 22cm Black', requiredQty: 2000, issuedQty: 600, uom: 'pcs' },
      { itemCode: 'INT-FUS-BLK-40', description: 'Fusible Interlining Woven 40gsm Black', requiredQty: 300, issuedQty: 150, uom: 'meters' },
      { itemCode: 'LBL-WVN-MAIN-SS26', description: 'Woven Main Label SS26 Collection', requiredQty: 2000, issuedQty: 0, uom: 'pcs' },
      { itemCode: 'THR-POLY-40-BLK', description: 'Polyester Sewing Thread 40/2 Black', requiredQty: 30, issuedQty: 0, uom: 'cones' },
    ],
  },
  {
    id: 4,
    poNumber: 'PRD-2026-004',
    style: 'AV-SS26-008',
    buyer: 'Marks & Spencer',
    orderQty: 2500,
    status: 'Planning',
    bom: [
      { itemCode: 'FAB-VRT-BLK', description: 'Viscose Rayon Twill Black', requiredQty: 337.5, issuedQty: 171.0, uom: 'kg' },
      { itemCode: 'ZIP-YKK-18CM-BLK', description: 'YKK Invisible Zipper 18cm Black', requiredQty: 2500, issuedQty: 800, uom: 'pcs' },
      { itemCode: 'LBL-WVN-MAIN-SS26', description: 'Woven Main Label SS26 Collection', requiredQty: 2500, issuedQty: 1000, uom: 'pcs' },
      { itemCode: 'THR-POLY-40-BLK', description: 'Polyester Sewing Thread 40/2 Black', requiredQty: 18, issuedQty: 10, uom: 'cones' },
      { itemCode: 'INT-FUS-WHT-40', description: 'Fusible Interlining Woven 40gsm White', requiredQty: 100, issuedQty: 50, uom: 'meters' },
    ],
  },
];

// ─── MOCK DASHBOARD STATS ───────────────────────────────────────────────────────
export const MOCK_DASHBOARD_STATS = {
  totalInwardValue: 2850000.0,
  fabricRolls: 83,
  accessoryItems: 15,
  pendingQC: 4,
  activeStyles: 5,
  pendingIssues: 2,
  grnThisMonth: 18,
  grnThisMonthValue: 1624130.0,
  qcPassRate: 92,
  stylesWithPendingMaterial: 3,
  stockByStyle: [
    { category: 'AV-SS26-001 (Nordstrom T-Shirt)', value: 452150.0, count: 4 },
    { category: 'AV-AW26-015 (Zara Denim Jacket)', value: 469000.0, count: 3 },
    { category: 'AV-SS26-003 (H&M Polo)', value: 393750.0, count: 2 },
    { category: 'AV-SS26-005 (Polyester Satin)', value: 199680.0, count: 2 },
    { category: 'AV-SS26-008 (M&S Blouse)', value: 430500.0, count: 3 },
    { category: 'AV-SS26-010 (Poplin Shirt)', value: 96000.0, count: 1 },
    { category: 'AV-SS26-012 (Linen Resort)', value: 220500.0, count: 1 },
  ],
  alerts: [
    { id: 1, type: 'low_stock', severity: 'warning', message: 'Polyester Sewing Thread 40/2 Navy — below reorder level (72 cones remaining)', module: 'accessories_stock', date: '2026-03-27' },
    { id: 2, type: 'qc_failed', severity: 'error', message: 'Linen Cotton Blend 55/45 (GRN-F-2026-0009) — QC Failed. GSM out of range, excessive defects.', module: 'fabric_qc', date: '2026-03-25' },
    { id: 3, type: 'pending_qc', severity: 'info', message: '100% Polyester Satin 75D (GRN-F-2026-0002) — QC pending approval for 3 days', module: 'fabric_qc', date: '2026-03-13' },
    { id: 4, type: 'low_stock', severity: 'warning', message: 'YKK Invisible Zipper 18cm Navy — approaching reorder level (2800 pcs)', module: 'accessories_stock', date: '2026-03-27' },
    { id: 5, type: 'pending_issue', severity: 'info', message: 'Denim Jacket AV-AW26-015 — partial fabric issue, 50% remaining to be issued', module: 'fabric_issues', date: '2026-03-24' },
    { id: 6, type: 'aging_stock', severity: 'warning', message: 'Cotton Jersey 40s Reactive (SL-A1) — 17 days in stock, prioritize for cutting', module: 'fabric_stock', date: '2026-03-27' },
    { id: 7, type: 'grn_pending', severity: 'info', message: '2 GRNs in Draft status awaiting submission', module: 'grn', date: '2026-03-27' },
    { id: 8, type: 'low_stock', severity: 'error', message: 'Elastic Band 25mm Black — below minimum level (1100 meters, min: 1200)', module: 'accessories_stock', date: '2026-03-27' },
  ],
};
