import { memo } from 'react';
import { Col, Row } from 'antd';
import {
  ScheduleOutlined, RiseOutlined, FieldTimeOutlined, StopOutlined, AlertOutlined, RobotOutlined,
} from '@ant-design/icons';
import StatCard from '../../../components/StatCard';

/** WF-01 KPI row. Every figure is derived; "plans auto-generated" is the FR-1.1 measure. */
const ControlTowerKpis = memo(function ControlTowerKpis({ kpis, loading }) {
  const k = kpis || {};
  const cards = [
    { title: k.blocked ? `Live orders planned (${k.blocked} blocked)` : 'Live orders planned', value: k.livePlanned, icon: <ScheduleOutlined />, color: 'var(--primary-color)' },
    { title: 'Forecast beyond commitment', value: k.forecastBeyond, icon: <RiseOutlined />, color: 'var(--error-color)' },
    { title: 'Open overdue activities', value: k.openOverdue, icon: <FieldTimeOutlined />, color: 'var(--warning-color)' },
    { title: 'Infeasible commitments', value: k.infeasible, icon: <StopOutlined />, color: 'var(--error-color)' },
    { title: 'Data-quality exceptions', value: k.dataQuality, icon: <AlertOutlined />, color: 'var(--warning-color)' },
    { title: 'Plans auto-generated', value: k.autoGeneratedPct, suffix: '%', icon: <RobotOutlined />, color: 'var(--success-color)' },
  ];
  return (
    <Row gutter={[12, 12]} style={{ marginBottom: 16 }}>
      {cards.map((c) => (
        <Col key={c.title} xs={12} md={8} xl={4}>
          <StatCard title={c.title} value={c.value ?? 0} suffix={c.suffix} icon={c.icon} color={c.color} loading={loading} />
        </Col>
      ))}
    </Row>
  );
});

export default ControlTowerKpis;
