/**
 * Static list of countries with ISO 3166-1 alpha-2 codes.
 * Used for Country dropdown (Select) and Zippopotam.us API lookups.
 */
export const COUNTRIES = [
  { label: 'Afghanistan', value: 'Afghanistan', iso2: 'AF' },
  { label: 'Albania', value: 'Albania', iso2: 'AL' },
  { label: 'Algeria', value: 'Algeria', iso2: 'DZ' },
  { label: 'Andorra', value: 'Andorra', iso2: 'AD' },
  { label: 'Angola', value: 'Angola', iso2: 'AO' },
  { label: 'Antigua and Barbuda', value: 'Antigua and Barbuda', iso2: 'AG' },
  { label: 'Argentina', value: 'Argentina', iso2: 'AR' },
  { label: 'Armenia', value: 'Armenia', iso2: 'AM' },
  { label: 'Australia', value: 'Australia', iso2: 'AU' },
  { label: 'Austria', value: 'Austria', iso2: 'AT' },
  { label: 'Azerbaijan', value: 'Azerbaijan', iso2: 'AZ' },
  { label: 'Bahamas', value: 'Bahamas', iso2: 'BS' },
  { label: 'Bahrain', value: 'Bahrain', iso2: 'BH' },
  { label: 'Bangladesh', value: 'Bangladesh', iso2: 'BD' },
  { label: 'Barbados', value: 'Barbados', iso2: 'BB' },
  { label: 'Belarus', value: 'Belarus', iso2: 'BY' },
  { label: 'Belgium', value: 'Belgium', iso2: 'BE' },
  { label: 'Belize', value: 'Belize', iso2: 'BZ' },
  { label: 'Benin', value: 'Benin', iso2: 'BJ' },
  { label: 'Bhutan', value: 'Bhutan', iso2: 'BT' },
  { label: 'Bolivia', value: 'Bolivia', iso2: 'BO' },
  { label: 'Bosnia and Herzegovina', value: 'Bosnia and Herzegovina', iso2: 'BA' },
  { label: 'Botswana', value: 'Botswana', iso2: 'BW' },
  { label: 'Brazil', value: 'Brazil', iso2: 'BR' },
  { label: 'Brunei', value: 'Brunei', iso2: 'BN' },
  { label: 'Bulgaria', value: 'Bulgaria', iso2: 'BG' },
  { label: 'Burkina Faso', value: 'Burkina Faso', iso2: 'BF' },
  { label: 'Burundi', value: 'Burundi', iso2: 'BI' },
  { label: 'Cabo Verde', value: 'Cabo Verde', iso2: 'CV' },
  { label: 'Cambodia', value: 'Cambodia', iso2: 'KH' },
  { label: 'Cameroon', value: 'Cameroon', iso2: 'CM' },
  { label: 'Canada', value: 'Canada', iso2: 'CA' },
  { label: 'Central African Republic', value: 'Central African Republic', iso2: 'CF' },
  { label: 'Chad', value: 'Chad', iso2: 'TD' },
  { label: 'Chile', value: 'Chile', iso2: 'CL' },
  { label: 'China', value: 'China', iso2: 'CN' },
  { label: 'Colombia', value: 'Colombia', iso2: 'CO' },
  { label: 'Comoros', value: 'Comoros', iso2: 'KM' },
  { label: 'Congo', value: 'Congo', iso2: 'CG' },
  { label: 'Costa Rica', value: 'Costa Rica', iso2: 'CR' },
  { label: 'Croatia', value: 'Croatia', iso2: 'HR' },
  { label: 'Cuba', value: 'Cuba', iso2: 'CU' },
  { label: 'Cyprus', value: 'Cyprus', iso2: 'CY' },
  { label: 'Czech Republic', value: 'Czech Republic', iso2: 'CZ' },
  { label: 'Denmark', value: 'Denmark', iso2: 'DK' },
  { label: 'Djibouti', value: 'Djibouti', iso2: 'DJ' },
  { label: 'Dominica', value: 'Dominica', iso2: 'DM' },
  { label: 'Dominican Republic', value: 'Dominican Republic', iso2: 'DO' },
  { label: 'Ecuador', value: 'Ecuador', iso2: 'EC' },
  { label: 'Egypt', value: 'Egypt', iso2: 'EG' },
  { label: 'El Salvador', value: 'El Salvador', iso2: 'SV' },
  { label: 'Equatorial Guinea', value: 'Equatorial Guinea', iso2: 'GQ' },
  { label: 'Eritrea', value: 'Eritrea', iso2: 'ER' },
  { label: 'Estonia', value: 'Estonia', iso2: 'EE' },
  { label: 'Eswatini', value: 'Eswatini', iso2: 'SZ' },
  { label: 'Ethiopia', value: 'Ethiopia', iso2: 'ET' },
  { label: 'Fiji', value: 'Fiji', iso2: 'FJ' },
  { label: 'Finland', value: 'Finland', iso2: 'FI' },
  { label: 'France', value: 'France', iso2: 'FR' },
  { label: 'Gabon', value: 'Gabon', iso2: 'GA' },
  { label: 'Gambia', value: 'Gambia', iso2: 'GM' },
  { label: 'Georgia', value: 'Georgia', iso2: 'GE' },
  { label: 'Germany', value: 'Germany', iso2: 'DE' },
  { label: 'Ghana', value: 'Ghana', iso2: 'GH' },
  { label: 'Greece', value: 'Greece', iso2: 'GR' },
  { label: 'Grenada', value: 'Grenada', iso2: 'GD' },
  { label: 'Guatemala', value: 'Guatemala', iso2: 'GT' },
  { label: 'Guinea', value: 'Guinea', iso2: 'GN' },
  { label: 'Guinea-Bissau', value: 'Guinea-Bissau', iso2: 'GW' },
  { label: 'Guyana', value: 'Guyana', iso2: 'GY' },
  { label: 'Haiti', value: 'Haiti', iso2: 'HT' },
  { label: 'Honduras', value: 'Honduras', iso2: 'HN' },
  { label: 'Hong Kong', value: 'Hong Kong', iso2: 'HK' },
  { label: 'Hungary', value: 'Hungary', iso2: 'HU' },
  { label: 'Iceland', value: 'Iceland', iso2: 'IS' },
  { label: 'India', value: 'India', iso2: 'IN' },
  { label: 'Indonesia', value: 'Indonesia', iso2: 'ID' },
  { label: 'Iran', value: 'Iran', iso2: 'IR' },
  { label: 'Iraq', value: 'Iraq', iso2: 'IQ' },
  { label: 'Ireland', value: 'Ireland', iso2: 'IE' },
  { label: 'Israel', value: 'Israel', iso2: 'IL' },
  { label: 'Italy', value: 'Italy', iso2: 'IT' },
  { label: 'Ivory Coast', value: 'Ivory Coast', iso2: 'CI' },
  { label: 'Jamaica', value: 'Jamaica', iso2: 'JM' },
  { label: 'Japan', value: 'Japan', iso2: 'JP' },
  { label: 'Jordan', value: 'Jordan', iso2: 'JO' },
  { label: 'Kazakhstan', value: 'Kazakhstan', iso2: 'KZ' },
  { label: 'Kenya', value: 'Kenya', iso2: 'KE' },
  { label: 'Kiribati', value: 'Kiribati', iso2: 'KI' },
  { label: 'Kuwait', value: 'Kuwait', iso2: 'KW' },
  { label: 'Kyrgyzstan', value: 'Kyrgyzstan', iso2: 'KG' },
  { label: 'Laos', value: 'Laos', iso2: 'LA' },
  { label: 'Latvia', value: 'Latvia', iso2: 'LV' },
  { label: 'Lebanon', value: 'Lebanon', iso2: 'LB' },
  { label: 'Lesotho', value: 'Lesotho', iso2: 'LS' },
  { label: 'Liberia', value: 'Liberia', iso2: 'LR' },
  { label: 'Libya', value: 'Libya', iso2: 'LY' },
  { label: 'Liechtenstein', value: 'Liechtenstein', iso2: 'LI' },
  { label: 'Lithuania', value: 'Lithuania', iso2: 'LT' },
  { label: 'Luxembourg', value: 'Luxembourg', iso2: 'LU' },
  { label: 'Macao', value: 'Macao', iso2: 'MO' },
  { label: 'Madagascar', value: 'Madagascar', iso2: 'MG' },
  { label: 'Malawi', value: 'Malawi', iso2: 'MW' },
  { label: 'Malaysia', value: 'Malaysia', iso2: 'MY' },
  { label: 'Maldives', value: 'Maldives', iso2: 'MV' },
  { label: 'Mali', value: 'Mali', iso2: 'ML' },
  { label: 'Malta', value: 'Malta', iso2: 'MT' },
  { label: 'Marshall Islands', value: 'Marshall Islands', iso2: 'MH' },
  { label: 'Mauritania', value: 'Mauritania', iso2: 'MR' },
  { label: 'Mauritius', value: 'Mauritius', iso2: 'MU' },
  { label: 'Mexico', value: 'Mexico', iso2: 'MX' },
  { label: 'Micronesia', value: 'Micronesia', iso2: 'FM' },
  { label: 'Moldova', value: 'Moldova', iso2: 'MD' },
  { label: 'Monaco', value: 'Monaco', iso2: 'MC' },
  { label: 'Mongolia', value: 'Mongolia', iso2: 'MN' },
  { label: 'Montenegro', value: 'Montenegro', iso2: 'ME' },
  { label: 'Morocco', value: 'Morocco', iso2: 'MA' },
  { label: 'Mozambique', value: 'Mozambique', iso2: 'MZ' },
  { label: 'Myanmar', value: 'Myanmar', iso2: 'MM' },
  { label: 'Namibia', value: 'Namibia', iso2: 'NA' },
  { label: 'Nauru', value: 'Nauru', iso2: 'NR' },
  { label: 'Nepal', value: 'Nepal', iso2: 'NP' },
  { label: 'Netherlands', value: 'Netherlands', iso2: 'NL' },
  { label: 'New Zealand', value: 'New Zealand', iso2: 'NZ' },
  { label: 'Nicaragua', value: 'Nicaragua', iso2: 'NI' },
  { label: 'Niger', value: 'Niger', iso2: 'NE' },
  { label: 'Nigeria', value: 'Nigeria', iso2: 'NG' },
  { label: 'North Korea', value: 'North Korea', iso2: 'KP' },
  { label: 'North Macedonia', value: 'North Macedonia', iso2: 'MK' },
  { label: 'Norway', value: 'Norway', iso2: 'NO' },
  { label: 'Oman', value: 'Oman', iso2: 'OM' },
  { label: 'Pakistan', value: 'Pakistan', iso2: 'PK' },
  { label: 'Palau', value: 'Palau', iso2: 'PW' },
  { label: 'Palestine', value: 'Palestine', iso2: 'PS' },
  { label: 'Panama', value: 'Panama', iso2: 'PA' },
  { label: 'Papua New Guinea', value: 'Papua New Guinea', iso2: 'PG' },
  { label: 'Paraguay', value: 'Paraguay', iso2: 'PY' },
  { label: 'Peru', value: 'Peru', iso2: 'PE' },
  { label: 'Philippines', value: 'Philippines', iso2: 'PH' },
  { label: 'Poland', value: 'Poland', iso2: 'PL' },
  { label: 'Portugal', value: 'Portugal', iso2: 'PT' },
  { label: 'Qatar', value: 'Qatar', iso2: 'QA' },
  { label: 'Romania', value: 'Romania', iso2: 'RO' },
  { label: 'Russia', value: 'Russia', iso2: 'RU' },
  { label: 'Rwanda', value: 'Rwanda', iso2: 'RW' },
  { label: 'Saint Kitts and Nevis', value: 'Saint Kitts and Nevis', iso2: 'KN' },
  { label: 'Saint Lucia', value: 'Saint Lucia', iso2: 'LC' },
  { label: 'Saint Vincent and the Grenadines', value: 'Saint Vincent and the Grenadines', iso2: 'VC' },
  { label: 'Samoa', value: 'Samoa', iso2: 'WS' },
  { label: 'San Marino', value: 'San Marino', iso2: 'SM' },
  { label: 'Sao Tome and Principe', value: 'Sao Tome and Principe', iso2: 'ST' },
  { label: 'Saudi Arabia', value: 'Saudi Arabia', iso2: 'SA' },
  { label: 'Senegal', value: 'Senegal', iso2: 'SN' },
  { label: 'Serbia', value: 'Serbia', iso2: 'RS' },
  { label: 'Seychelles', value: 'Seychelles', iso2: 'SC' },
  { label: 'Sierra Leone', value: 'Sierra Leone', iso2: 'SL' },
  { label: 'Singapore', value: 'Singapore', iso2: 'SG' },
  { label: 'Slovakia', value: 'Slovakia', iso2: 'SK' },
  { label: 'Slovenia', value: 'Slovenia', iso2: 'SI' },
  { label: 'Solomon Islands', value: 'Solomon Islands', iso2: 'SB' },
  { label: 'Somalia', value: 'Somalia', iso2: 'SO' },
  { label: 'South Africa', value: 'South Africa', iso2: 'ZA' },
  { label: 'South Korea', value: 'South Korea', iso2: 'KR' },
  { label: 'South Sudan', value: 'South Sudan', iso2: 'SS' },
  { label: 'Spain', value: 'Spain', iso2: 'ES' },
  { label: 'Sri Lanka', value: 'Sri Lanka', iso2: 'LK' },
  { label: 'Sudan', value: 'Sudan', iso2: 'SD' },
  { label: 'Suriname', value: 'Suriname', iso2: 'SR' },
  { label: 'Sweden', value: 'Sweden', iso2: 'SE' },
  { label: 'Switzerland', value: 'Switzerland', iso2: 'CH' },
  { label: 'Syria', value: 'Syria', iso2: 'SY' },
  { label: 'Taiwan', value: 'Taiwan', iso2: 'TW' },
  { label: 'Tajikistan', value: 'Tajikistan', iso2: 'TJ' },
  { label: 'Tanzania', value: 'Tanzania', iso2: 'TZ' },
  { label: 'Thailand', value: 'Thailand', iso2: 'TH' },
  { label: 'Timor-Leste', value: 'Timor-Leste', iso2: 'TL' },
  { label: 'Togo', value: 'Togo', iso2: 'TG' },
  { label: 'Tonga', value: 'Tonga', iso2: 'TO' },
  { label: 'Trinidad and Tobago', value: 'Trinidad and Tobago', iso2: 'TT' },
  { label: 'Tunisia', value: 'Tunisia', iso2: 'TN' },
  { label: 'Turkey', value: 'Turkey', iso2: 'TR' },
  { label: 'Turkmenistan', value: 'Turkmenistan', iso2: 'TM' },
  { label: 'Tuvalu', value: 'Tuvalu', iso2: 'TV' },
  { label: 'Uganda', value: 'Uganda', iso2: 'UG' },
  { label: 'Ukraine', value: 'Ukraine', iso2: 'UA' },
  { label: 'United Arab Emirates', value: 'United Arab Emirates', iso2: 'AE' },
  { label: 'United Kingdom', value: 'United Kingdom', iso2: 'GB' },
  { label: 'United States', value: 'United States', iso2: 'US' },
  { label: 'Uruguay', value: 'Uruguay', iso2: 'UY' },
  { label: 'Uzbekistan', value: 'Uzbekistan', iso2: 'UZ' },
  { label: 'Vanuatu', value: 'Vanuatu', iso2: 'VU' },
  { label: 'Vatican City', value: 'Vatican City', iso2: 'VA' },
  { label: 'Venezuela', value: 'Venezuela', iso2: 'VE' },
  { label: 'Vietnam', value: 'Vietnam', iso2: 'VN' },
  { label: 'Yemen', value: 'Yemen', iso2: 'YE' },
  { label: 'Zambia', value: 'Zambia', iso2: 'ZM' },
  { label: 'Zimbabwe', value: 'Zimbabwe', iso2: 'ZW' },
];

/**
 * Get ISO2 country code from country name.
 * Used for Zippopotam.us API calls.
 */
export const getCountryISO2 = (countryName) =>
  COUNTRIES.find((c) => c.value === countryName)?.iso2 || null;
