/**
 * The Time & Action read models the screens consume (mock API, Round 1). Imports the
 * service layer directly: no browser, no backend. Guards the contract Round 2's
 * /api/v1/tna endpoints must keep, and the CR rules that live in the read models.
 */
import { test, expect } from '@playwright/test';
import * as api from '../../../src/services/tna/tnaService.js';

test.describe.configure({ mode: 'serial' });

test.describe('Time & Action read models', () => {
  test('WF-01 — Control Tower lists live and blocked orders with both commitments', async () => {
    const { rows, kpis } = await api.listPlans();
    const worked = rows.find((r) => r.orderNo === 'SG/26-27/1012');
    expect(worked).toMatchObject({
      originalCommitment: '2026-11-03', latestCommitment: '2026-12-07', commitmentMovement: 34,
      forecastDispatch: '2026-11-23', delayOriginal: 20, delayLatest: -14, healthLatest: 'GREEN', healthOriginal: 'RED',
      progress: { done: 12, total: 28 }, openCriticalLatest: 0,
    });
    expect(rows.find((r) => r.orderNo === 'SG/26-27/1023').healthLatest).toBe('BLOCKED');
    expect(rows.find((r) => r.orderNo === 'SG/26-27/1031').healthLatest).toBe('INFEASIBLE');
    expect(kpis.blocked).toBe(2);
    expect(kpis.autoGeneratedPct).toBe(100);
  });

  test('WF-05 — activity detail carries evidence, attribution and network impact', async () => {
    const d = await api.getActivityDetail(1012, 'A13');
    expect(d.activity.evidence.sourceRecord).toBe('GRN/26-27/11847');
    expect(d.activity.partials).toHaveLength(2);
    expect(d.attribution.category).toBe('SUPPLIER');
    expect(d.impact.activitiesMoved).toBeGreaterThan(0);
    const fit = await api.getActivityDetail(1012, 'A05');
    expect(fit.attribution.category).toBe('REASON_UNAVAILABLE');
  });

  test('WF-06 — versions, baseline comparison and the commitment register', async () => {
    const versions = await api.listVersions(1012);
    expect(versions[0]).toMatchObject({ versionNo: 1, changeType: 'GENERATION', reason: 'Baseline set' });
    expect(versions.find((v) => v.changeType === 'COMMITMENT_REVISION').activitiesMoved).toBe(0);
    const cmp = await api.getBaselineComparison(1012);
    expect(cmp.baselineDispatch).toBe('2026-11-02');
    expect(cmp.netImpactForecast).toBe(21);
    const { register } = await api.getCommitments(1012);
    expect(register.map((c) => [c.type, c.date])).toEqual([['ORIGINAL', '2026-11-03'], ['REVISED', '2026-12-07']]);
    const diff = await api.compareVersions(1012, 1, versions.length);
    expect(diff.find((r) => r.code === 'A13').delta).toBe(12);
  });

  test('WF-08 — exceptions: blocking, warnings, awaiting-source and duplicates', async () => {
    const { rows, kpis } = await api.listExceptions();
    const types = rows.map((x) => x.type);
    ['IDENTITY_UNRESOLVED', 'MISSING_MANDATORY_INPUT', 'INFEASIBLE_COMMITMENT', 'PROVISIONAL_ACTIVITIES', 'POST_BASELINE_ADDENDUM', 'AWAITING_SOURCE', 'QUALITY_REJECTION', 'RECONCILIATION_MISMATCH']
      .forEach((t) => expect.soft(types, t).toContain(t));
    expect(kpis.blocking).toBe(3);
    expect(kpis.duplicatesSuppressed).toBe(1);
  });

  test('FR-6.4 — "Report data issue" raises a task and writes nothing into the plan', async () => {
    const before = await api.getPlan(1012);
    const issue = await api.reportDataIssue({ planId: 1012, activityCode: 'A13', text: 'GRN date looks a day late', by: 'Planner' });
    expect(issue).toMatchObject({ type: 'DATA_ISSUE_REPORTED', sourceRecord: 'GRN/26-27/11847', ownerRole: 'Stores' });
    expect(await api.getPlan(1012)).toEqual(before);
  });

  test('WF-07 — attribution is a share of net order impact; commitment movement is separate', async () => {
    const a = await api.getAnalytics({ months: 0 });
    expect(a.kpis.orders).toBeGreaterThan(25);
    const share = a.attribution.reduce((s, r) => s + r.share, 0);
    expect(share).toBeGreaterThanOrEqual(98);
    expect(share).toBeLessThanOrEqual(102);
    expect(a.attribution.map((r) => r.category)).toContain('REASON_UNAVAILABLE');
    expect(a.commitmentByBuyer.some((b) => b.revised > 0)).toBe(true);
    expect(a.masterBias.length).toBeGreaterThan(0);
  });

  test('D-06 / FR-9.2 — acknowledging the infeasible plan and resolving identity are the only plan actions', async () => {
    const ack = await api.acknowledgeInfeasible(1031, { by: 'K. Rao', reason: 'Buyer agreed air freight for 30%' });
    expect(ack.status).toBe('ACTIVE');
    expect(ack.healthLatest).toBe('INFEASIBLE');
    const { rows } = await api.listExceptions();
    const identity = rows.find((x) => x.type === 'IDENTITY_UNRESOLVED');
    const resolved = await api.resolveException(identity.id, { by: 'Data steward', note: 'CP/6102/B mapped to SG/26-27/1023 line 1' });
    expect(resolved.regenerated).toBe('ACTIVE');
    const plan = await api.getPlan(1023);
    expect(plan.activities.find((a) => a.code === 'A02').actualDate).toBe('2026-09-04');
  });
});
