import { Modal, Descriptions, Space } from 'antd';
import { QrcodeOutlined } from '@ant-design/icons';
import dayjs from 'dayjs';

/**
 * ENH-05 — bundle ticket preview. QR encodes
 * BundleID|StyleNo|Size|Color|Qty|CutDate|CutPONo; real PDF/thermal label at
 * backend integration (this modal shows the ticket layout for design review).
 */
const BundleTicketPreview = ({ ticket, onClose }) => {
  if (!ticket) return null;
  const { bundle, po } = ticket;
  const qrPayload = [bundle.id, po?.styleNo, bundle.size, po?.color, bundle.qty, dayjs().format('YYYYMMDD'), po?.cutPoNo].join('|');
  return (
    <Modal open onCancel={onClose} footer={null} title={`Bundle Ticket — B-${bundle.bundleNo}`} width={420}>
      <div style={{ border: '1px dashed var(--border-color, #d9d9d9)', borderRadius: 8, padding: 16 }}>
        <Space align="start" size="large">
          <div style={{
            width: 110, height: 110, display: 'flex', flexDirection: 'column', alignItems: 'center',
            justifyContent: 'center', border: '1px solid var(--border-color, #d9d9d9)', borderRadius: 4,
          }}>
            <QrcodeOutlined style={{ fontSize: 72 }} />
            <span style={{ fontSize: 10, color: 'var(--text-secondary)' }}>QR preview</span>
          </div>
          <Descriptions size="small" column={1}
            items={[
              { key: 'b', label: 'Bundle', children: <strong>B-{bundle.bundleNo}</strong> },
              { key: 's', label: 'Style', children: po?.styleNo },
              { key: 'z', label: 'Size', children: `${bundle.size} · ${bundle.qty} pcs` },
              { key: 'c', label: 'Color', children: po?.color },
              { key: 'r', label: 'Serials', children: bundle.range },
              { key: 'p', label: 'Cut PO', children: po?.cutPoNo },
            ]} />
        </Space>
        <div style={{ marginTop: 12, fontSize: 11, color: 'var(--text-secondary)', wordBreak: 'break-all' }}>
          QR data: {qrPayload}
        </div>
      </div>
      <p style={{ marginTop: 12, color: 'var(--text-secondary)', fontSize: 12 }}>
        Printable ticket sheets (3×8 on A4 / thermal labels) are generated by the backend at integration; scanning at
        sewing input will auto-fill the sewing entry form.
      </p>
    </Modal>
  );
};

export default BundleTicketPreview;
