/**
 * In-memory mock API for the TNA module (design phase). Plans are generated by
 * the §8 engine at init — never hand-dated — then decorated on read with the
 * derived figures (§10.1/§12): status, deviation, projection, RAG, progress.
 * State persists for the browser session so the workflows are clickable:
 * actual capture → projection shift → re-plan → approval cascade → version.
 */
import dayjs from 'dayjs';
import { generateSchedule, projectDispatch, forwardPass, hasCycle } from './tnaScheduler';
import { DEVIATION_REMARK_THRESHOLD } from '../../utils/tnaConstants';
import * as seed from './tnaMockData';

const delay = (ms = 150) => new Promise((r) => setTimeout(r, ms));
const clone = (v) => JSON.parse(JSON.stringify(v));
const today = () => dayjs().startOf('day');
const fail = (code, msg) => { const e = new Error(msg); e.code = code; throw e; };

const db = { plans: [], replans: [], audit: [], activities: clone(seed.seedActivities), templates: clone(seed.seedTemplates), auditSeq: 1 };

const logAudit = (planId, activityCode, field, oldValue, newValue, changeType, user, extra = {}) => {
  db.audit.unshift({ id: db.auditSeq++, planId, activityCode, field, oldValue, newValue, changeType, user, timestamp: dayjs().format('YYYY-MM-DD HH:mm'), ...extra });
};

// §7.4 — template resolution precedence
const resolveTemplate = (buyer, productType) => {
  const active = db.templates.filter((t) => t.status === 'ACTIVE');
  return active.find((t) => t.buyer === buyer && t.productType === productType)
    || active.find((t) => t.buyer === buyer && !t.productType)
    || active.find((t) => !t.buyer && t.productType === productType)
    || active.find((t) => !t.buyer && !t.productType)
    || null;
};

const SOURCE_REF_PREFIX = { Order: 'SO', Purchase: 'PO', Sampling: 'SMP', Store: 'GRN', Production: 'PRD', QC: 'INS', Shipment: 'SHP' };

// ── Init: generate every plan through the engine, then replay seeded actuals ─
const buildPlans = () => {
  const actMap = Object.fromEntries(db.activities.map((a) => [a.code, a]));
  seed.seedOrders.forEach((o) => {
    const tpl = resolveTemplate(o.buyer, o.productType);
    const orderReceived = today().subtract(o.receivedAgo, 'day').format('YYYY-MM-DD');
    const etd = dayjs(orderReceived).add(o.leadtime, 'day').format('YYYY-MM-DD');
    const sched = generateSchedule({ templateLines: tpl.lines, leadtime: o.leadtime, orderReceived, routeOps: o.routeOps });
    const plan = {
      id: o.id, orderId: o.id, orderNo: o.orderNo, buyer: o.buyer, styleNo: o.styleNo,
      productType: o.productType, qty: o.qty, uom: o.uom, merchandiser: o.merchandiser,
      orderReceived, etd, leadtime: o.leadtime, templateCode: tpl.templateCode, templateVersion: tpl.version,
      planVersion: 1, replanCount: 0,
      planStatus: sched.feasibility === 'INFEASIBLE' ? 'DRAFT' : (o.planStatus || 'ACTIVE'),
      feasibility: sched.feasibility, compressedDays: sched.compressedDays, compressedFrom: sched.compressedFrom,
      shortfallDays: sched.shortfallDays, plannedDispatch: sched.plannedDispatch, versions: [],
      lines: sched.lines.map((l) => ({
        ...l, ...actMap[l.code], baselineDate: l.plannedDate, // §8.9 — frozen v1
        responsible: actMap[l.code].defaultRole === 'Merchandiser' ? o.merchandiser : actMap[l.code].defaultRole,
        actualDate: null, actualSource: null, actualSourceRef: null, remarks: null, attachmentName: null, replanDate: null,
      })),
    };
    // Replay actuals profile (skips anything that would land in the future)
    const throughIdx = plan.lines.findIndex((l) => l.code === o.actuals.through);
    plan.lines.forEach((l, i) => {
      if (i > throughIdx) return;
      const actual = dayjs(l.plannedDate).add(o.actuals.late[l.code] || 0, 'day');
      if (actual.isAfter(today())) return;
      l.actualDate = actual.format('YYYY-MM-DD');
      const sys = l.sourceModule !== 'Manual';
      l.actualSource = sys ? `${l.sourceModule} module` : `Manual · ${plan.merchandiser}`;
      l.actualSourceRef = sys ? `${SOURCE_REF_PREFIX[l.sourceModule]}-26-${String(1000 + plan.id * 20 + i)}` : null;
      if (l.requiresAttachment) l.attachmentName = `${l.code}_${plan.orderNo}_approval.pdf`;
      logAudit(plan.id, l.code, 'actualDate', null, l.actualDate, sys ? 'AUTO_CAPTURE' : 'MANUAL_ENTRY', sys ? 'system' : plan.merchandiser, { sourceRef: l.actualSourceRef });
    });
    db.plans.push(plan);
  });
  seed.seedReplans.forEach((r) => {
    const plan = db.plans.find((p) => p.id === r.planId);
    const lineRow = plan.lines.find((l) => l.code === r.activityCode);
    db.replans.push({
      ...r, orderNo: plan.orderNo, buyer: plan.buyer, styleNo: plan.styleNo, activityName: lineRow.name,
      currentDate: lineRow.plannedDate, proposedDate: dayjs(lineRow.plannedDate).add(r.proposedShiftDays, 'day').format('YYYY-MM-DD'),
      raisedOn: today().subtract(r.raisedAgo, 'day').format('YYYY-MM-DD'),
    });
  });
};
buildPlans();

// ── Derived figures (§10.1 / §12.2 / §12.3) ────────────────────────────────
const lineStatus = (l) => {
  if (l.actualDate) return dayjs(l.actualDate).isAfter(dayjs(l.baselineDate)) ? 'COMPLETED_LATE' : 'COMPLETED_ON_TIME';
  const t = today();
  if (t.isAfter(dayjs(l.plannedDate))) return l.floatDays <= 0 ? 'OVERDUE_CRITICAL' : 'OVERDUE';
  if (!t.isBefore(dayjs(l.plannedDate).subtract(l.reminderLeadDays, 'day'))) return 'DUE_SOON';
  return 'NOT_STARTED';
};

export const decoratePlan = (plan) => {
  const lines = plan.lines.map((l) => ({
    ...l,
    status: lineStatus(l),
    deviationDays: l.actualDate ? dayjs(l.actualDate).diff(dayjs(l.baselineDate), 'day') : null, // §12.1 — null, never zero
    deviationVsPlan: l.actualDate ? dayjs(l.actualDate).diff(dayjs(l.plannedDate), 'day') : null,
  }));
  const projectedDispatch = projectDispatch(plan.lines, plan.orderReceived);
  const projectedDelay = dayjs(projectedDispatch).diff(dayjs(plan.etd), 'day');
  const done = lines.filter((l) => l.actualDate).length;
  const overdueCriticals = lines.filter((l) => l.status === 'OVERDUE_CRITICAL').length;
  const rag = plan.feasibility === 'INFEASIBLE' || projectedDelay > 0 ? 'RED'
    : (overdueCriticals > 0 || lines.some((l) => l.status === 'OVERDUE') ? 'AMBER' : 'GREEN');
  const nextMilestone = lines.find((l) => l.milestone && !l.actualDate) || null;
  return {
    ...plan, lines, projectedDispatch, projectedDelay, overdueCriticals, rag,
    progressPct: Math.round((done / lines.length) * 100),
    nextMilestone: nextMilestone ? { code: nextMilestone.code, name: nextMilestone.name, plannedDate: nextMilestone.plannedDate, status: nextMilestone.status } : null,
  };
};

// ── Plans ───────────────────────────────────────────────────────────────────
export const listPlans = async () => { await delay(); return db.plans.map((p) => decoratePlan(p)); };
export const getPlan = async (id) => {
  await delay();
  const plan = db.plans.find((p) => p.id === Number(id));
  return plan ? decoratePlan(plan) : null;
};
export const getPlanVersions = async (id) => { await delay(); return clone(db.plans.find((p) => p.id === Number(id))?.versions || []); };
export const getAuditTrail = async (planId) => { await delay(); return clone(db.audit.filter((a) => a.planId === Number(planId))); };

// ── Actual capture (manual path — §10.2 / VR-09..12, VR-18) ────────────────
export const recordActual = async (planId, code, { actualDate, remarks, attachmentName, user }) => {
  await delay();
  const plan = db.plans.find((p) => p.id === Number(planId));
  const l = plan.lines.find((x) => x.code === code);
  if (['CANCELLED', 'ON_HOLD'].includes(plan.planStatus)) fail('VR-18', `This plan is ${plan.planStatus}. Dates cannot be recorded.`);
  const d = dayjs(actualDate);
  if (d.isAfter(today())) fail('VR-09', 'An actual date cannot be later than today.');
  const badPred = l.predecessors.find((p) => { const pl = plan.lines.find((x) => x.code === p); return pl?.actualDate && d.isBefore(dayjs(pl.actualDate)); });
  if (badPred) fail('VR-10', `This date is earlier than the completion of ${plan.lines.find((x) => x.code === badPred).name}.`);
  if (l.requiresAttachment && !attachmentName) fail('VR-11', `Activity ${l.name} requires a supporting document before the actual date can be saved.`);
  const deviation = d.diff(dayjs(l.baselineDate), 'day');
  if (deviation > DEVIATION_REMARK_THRESHOLD && !remarks) fail('VR-12', `This activity is ${deviation} days late. A remark is required.`);
  logAudit(plan.id, code, 'actualDate', l.actualDate, d.format('YYYY-MM-DD'), 'MANUAL_ENTRY', user || seed.CURRENT_USER);
  Object.assign(l, { actualDate: d.format('YYYY-MM-DD'), actualSource: `Manual · ${user || seed.CURRENT_USER}`, remarks: remarks || l.remarks, attachmentName: attachmentName || l.attachmentName });
  if (code === 'A24') plan.planStatus = 'COMPLETED';
  return decoratePlan(plan);
};

// ── Re-plan workflow (§13) ──────────────────────────────────────────────────
/** §13.2 cascade — forward-simulate with the proposed date; lines carrying an
 *  actual are pinned; nothing is ever pulled earlier than its committed plan. */
const cascadeOf = (plan, code, proposedDate) => {
  const anchor = dayjs(plan.orderReceived);
  const shift = dayjs(proposedDate).diff(dayjs(plan.lines.find((l) => l.code === code).plannedDate), 'day');
  const sim = plan.lines.map((l) => ({
    ...l, effectiveDays: l.code === code ? l.effectiveDays + shift : l.effectiveDays,
  }));
  const { es } = forwardPass(sim.map((l) => (l.actualDate
    ? { ...l, predecessors: [], effectiveDays: dayjs(l.actualDate).diff(anchor, 'day') }
    : l)));
  return plan.lines
    .filter((l) => !l.actualDate)
    .map((l) => {
      const computed = anchor.add(Math.max(es[l.code], dayjs(l.plannedDate).diff(anchor, 'day')), 'day');
      return { code: l.code, name: l.name, oldDate: l.plannedDate, newDate: computed.format('YYYY-MM-DD'), shiftDays: computed.diff(dayjs(l.plannedDate), 'day') };
    })
    .filter((c) => c.shiftDays !== 0);
};

export const proposeReplan = async ({ planId, code, proposedDate, reasonCode, justification, user }) => {
  await delay();
  const plan = db.plans.find((p) => p.id === Number(planId));
  const l = plan.lines.find((x) => x.code === code);
  if (!reasonCode || !justification) fail('VR-13', 'Select a reason and enter a justification for this re-plan.');
  const badPred = l.predecessors.find((p) => { const pl = plan.lines.find((x) => x.code === p); return pl?.actualDate && dayjs(proposedDate).isBefore(dayjs(pl.actualDate)); });
  if (badPred) fail('VR-14', `The proposed date is earlier than the completion of ${plan.lines.find((x) => x.code === badPred).name}.`);
  const decorated = decoratePlan(plan);
  const row = {
    id: db.replans.reduce((m, r) => Math.max(m, r.id), 0) + 1, planId: plan.id, orderNo: plan.orderNo,
    buyer: plan.buyer, styleNo: plan.styleNo, activityCode: code, activityName: l.name,
    currentDate: l.plannedDate, proposedDate, reasonCode, justification, workflowStatus: 'PENDING_APPROVAL',
    raisedBy: user || seed.CURRENT_USER, raisedOn: today().format('YYYY-MM-DD'),
    projectedDispatchBefore: decorated.projectedDispatch,
  };
  db.replans.unshift(row);
  return clone(row);
};

export const listReplans = async () => {
  await delay();
  return db.replans.map((r) => ({ ...clone(r), cascade: cascadeOf(db.plans.find((p) => p.id === r.planId), r.activityCode, r.proposedDate) }));
};

export const actionReplan = async (id, action, { remarks, user } = {}) => {
  await delay();
  const r = db.replans.find((x) => x.id === Number(id));
  const actor = user || seed.CURRENT_USER;
  if (actor === r.raisedBy && action === 'APPROVE') fail('VR-15', 'You cannot approve a re-plan that you raised.');
  const plan = db.plans.find((p) => p.id === r.planId);
  if (action === 'APPROVE') {
    // Snapshot current version, cascade (§13.2 — lines with actuals excluded), bump version
    plan.versions.unshift({ versionNo: plan.planVersion, generatedOn: today().format('YYYY-MM-DD'), reasonCode: r.reasonCode, justification: r.justification, lines: plan.lines.map((l) => ({ code: l.code, name: l.name, plannedDate: l.plannedDate, floatDays: l.floatDays })) });
    cascadeOf(plan, r.activityCode, r.proposedDate).forEach((c) => {
      const l = plan.lines.find((x) => x.code === c.code);
      logAudit(plan.id, c.code, 'plannedDate', c.oldDate, c.newDate, 'APPROVED_REPLAN', actor, { reasonCode: r.reasonCode, approver: actor });
      l.plannedDate = c.newDate;
      l.floatDays = dayjs(l.latestAllowableDate).diff(dayjs(l.plannedDate), 'day');
      l.isCritical = l.floatDays <= 0;
    });
    plan.planVersion += 1;
    plan.replanCount += 1;
    r.workflowStatus = 'APPROVED';
    r.projectedDispatchAfter = decoratePlan(plan).projectedDispatch;
  } else {
    r.workflowStatus = action === 'REJECT' ? 'REJECTED' : 'RETURNED';
  }
  Object.assign(r, { approverId: actor, actionedOn: today().format('YYYY-MM-DD'), approverRemarks: remarks || r.approverRemarks });
  return clone(r);
};

// ── My activities ───────────────────────────────────────────────────────────
export const listMyActivities = async (user = seed.CURRENT_USER) => {
  await delay();
  const urgency = { OVERDUE_CRITICAL: 0, OVERDUE: 1, DUE_SOON: 2, NOT_STARTED: 3, COMPLETED_LATE: 4, COMPLETED_ON_TIME: 5 };
  return db.plans
    .filter((p) => ['ACTIVE'].includes(p.planStatus))
    .flatMap((p) => decoratePlan(p).lines
      .filter((l) => l.responsible === user && !l.actualDate)
      .map((l) => ({ ...l, planId: p.id, orderNo: p.orderNo, buyer: p.buyer, styleNo: p.styleNo, etd: p.etd })))
    .sort((a, b) => (urgency[a.status] - urgency[b.status]) || dayjs(a.plannedDate).diff(dayjs(b.plannedDate)));
};

// ── Masters ─────────────────────────────────────────────────────────────────
export const listActivities = async () => { await delay(); return clone(db.activities); };
export const saveActivity = async (payload) => {
  await delay();
  const i = db.activities.findIndex((a) => a.code === payload.code);
  if (i >= 0) db.activities[i] = { ...db.activities[i], ...payload }; else db.activities.push(payload);
  return clone(payload);
};

const templateFigures = (lines) => ({
  baselineCriticalPath: forwardPass(lines.map((l) => ({ ...l, effectiveDays: l.baseDays }))).criticalPath,
  minFeasibleLeadtime: forwardPass(lines.map((l) => ({ ...l, effectiveDays: l.fixed ? l.baseDays : l.minDays }))).criticalPath,
});
export const listTemplates = async () => { await delay(); return db.templates.map((t) => ({ ...clone(t), ...templateFigures(t.lines) })); };
export const saveTemplate = async (payload) => {
  await delay();
  const lines = payload.lines;
  if (hasCycle(lines)) fail('VR-04', `Template ${payload.templateCode} contains a circular dependency. Save aborted.`);
  const codes = new Set(lines.map((l) => l.code));
  const noPred = lines.filter((l, i) => i > 0 && l.predecessors.length === 0);
  if (noPred.length) fail('VR-05', `Activity ${noPred[0].code} has no predecessor. Every activity except the first must have one.`);
  const withSucc = new Set(lines.flatMap((l) => l.predecessors));
  const noSucc = lines.filter((l) => l.code !== 'A24' && !withSucc.has(l.code) && codes.has(l.code));
  if (noSucc.length) fail('VR-06', `Activity ${noSucc[0].code} has no successor and cannot influence the plan.`);
  const badMinMax = lines.find((l) => l.minDays > l.maxDays);
  if (badMinMax) fail('VR-07', `Minimum days cannot be greater than maximum days for activity ${badMinMax.code}.`);
  const badFixed = lines.find((l) => l.fixed && l.minDays !== l.maxDays);
  if (badFixed) fail('VR-08', 'A fixed-duration activity must have equal minimum and maximum days.');
  const badRoute = lines.find((l) => l.conditionalOnRoute && !l.routeOperation);
  if (badRoute) fail('VR-16', `Select the route operation for conditional activity ${badRoute.code}.`);
  const i = db.templates.findIndex((t) => t.id === payload.id);
  if (i >= 0) db.templates[i] = { ...db.templates[i], ...payload, version: db.templates[i].version + 1 };
  else db.templates.push({ ...payload, id: db.templates.reduce((m, t) => Math.max(m, t.id), 0) + 1, version: 1 });
  return clone(payload);
};

// ── Analytics (§15) — computed live from state, never stored ───────────────
export const getAnalytics = async () => {
  await delay();
  const decorated = db.plans.map((p) => decoratePlan(p));
  const allLines = decorated.flatMap((p) => p.lines.map((l) => ({ ...l, orderNo: p.orderNo, buyer: p.buyer })));
  const completed = allLines.filter((l) => l.actualDate);
  const pct = (n, d) => (d ? Math.round((n / d) * 100) : null);

  const onTimeByActivity = db.activities.map((a) => {
    const rows = completed.filter((l) => l.code === a.code);
    return { code: a.code, name: a.name, group: a.group, completed: rows.length, onTimePct: pct(rows.filter((l) => l.deviationDays <= 0).length, rows.length) };
  }).filter((r) => r.completed > 0);

  const pairs = [['A03', 'A04', 'Lab Dip / Strike-off'], ['A05', 'A06', 'Fit sample'], ['A10', 'A11', 'PP sample']];
  const buyerTurnaround = [...new Set(decorated.map((p) => p.buyer))].map((buyer) => {
    const row = { buyer };
    pairs.forEach(([sub, app, label]) => {
      const days = decorated.filter((p) => p.buyer === buyer).map((p) => {
        const s = p.lines.find((l) => l.code === sub)?.actualDate;
        const a = p.lines.find((l) => l.code === app)?.actualDate;
        return s && a ? dayjs(a).diff(dayjs(s), 'day') : null;
      }).filter((v) => v != null);
      row[label] = days.length ? Math.round((days.reduce((x, y) => x + y, 0) / days.length) * 10) / 10 : null;
    });
    return row;
  });

  const lateLines = completed.filter((l) => l.deviationDays > 0);
  const delaySplit = {
    buyerDependent: lateLines.filter((l) => l.buyerDependent).reduce((s, l) => s + l.deviationDays, 0),
    internal: lateLines.filter((l) => !l.buyerDependent).reduce((s, l) => s + l.deviationDays, 0),
  };
  const delayByReason = seed.MERCHANDISERS && db.replans.reduce((acc, r) => {
    acc[r.reasonCode] = (acc[r.reasonCode] || 0) + Math.max(0, dayjs(r.proposedDate).diff(dayjs(r.currentDate), 'day'));
    return acc;
  }, {});

  const templateEffectiveness = db.activities.map((a) => {
    const rows = completed.filter((l) => l.code === a.code);
    const actualDur = (l) => {
      const plan = decorated.find((p) => p.orderNo === l.orderNo);
      const predEnd = l.predecessors.length
        ? Math.max(...l.predecessors.map((c) => dayjs(plan.lines.find((x) => x.code === c)?.actualDate || plan.lines.find((x) => x.code === c)?.plannedDate).valueOf()))
        : dayjs(plan.orderReceived).valueOf();
      return dayjs(l.actualDate).diff(dayjs(predEnd), 'day');
    };
    const avg = rows.length ? Math.round((rows.reduce((s, l) => s + actualDur(l), 0) / rows.length) * 10) / 10 : null;
    return { code: a.code, name: a.name, plannedAvg: rows.length ? Math.round((rows.reduce((s, l) => s + l.effectiveDays, 0) / rows.length) * 10) / 10 : null, actualAvg: avg, samples: rows.length };
  }).filter((r) => r.samples > 0);

  return {
    onTimeByActivity,
    buyerTurnaround,
    delayByReason,
    delaySplit,
    replanRegister: clone(db.replans.filter((r) => r.workflowStatus === 'APPROVED')),
    replanAll: clone(db.replans),
    infeasibleOrders: decorated.filter((p) => p.feasibility === 'INFEASIBLE').map((p) => ({ orderNo: p.orderNo, buyer: p.buyer, styleNo: p.styleNo, leadtime: p.leadtime, shortfallDays: p.shortfallDays, etd: p.etd })),
    criticalExposure: decorated
      .filter((p) => p.planStatus === 'ACTIVE')
      .map((p) => ({ planId: p.id, orderNo: p.orderNo, buyer: p.buyer, styleNo: p.styleNo, etd: p.etd, rag: p.rag, minFloat: Math.min(...p.lines.filter((l) => !l.actualDate).map((l) => l.floatDays)), overdueCriticals: p.overdueCriticals }))
      .sort((a, b) => a.minFloat - b.minFloat),
    templateEffectiveness,
  };
};
