/**
 * TNA seed data (design/mock phase). The 24-activity master and global template
 * are the indicative baseline of BRD §7.5 — critical path 89 days, floor 56.
 * Orders are seeded relative to "today" so the Control Tower always shows a
 * live RAG spread; plans are GENERATED by the §8 engine, never hand-dated.
 */

// ── Activity master (§7.1 / §11) ────────────────────────────────────────────
const act = (code, name, shortName, group, role, source, flags = {}) => ({
  code, name, shortName, group, defaultRole: role, sourceModule: source,
  milestone: !!flags.m, buyerDependent: !!flags.b, requiresAttachment: !!flags.a, active: true,
});

export const seedActivities = [
  act('A01', 'Order receipt (Buyer PO)', 'Order Rcpt', 'Order', 'Merchandiser', 'Order', { m: 1 }),
  act('A02', 'PO issue for Fabric & Trims', 'PO Issue', 'Material', 'Merchandiser', 'Purchase'),
  act('A03', 'Strike-off / Lab Dip submission', 'S/Off-L/Dip Sub', 'Approval', 'Merchandiser', 'Sampling'),
  act('A04', 'Strike-off / Lab Dip approval', 'S/Off-L/Dip App', 'Approval', 'Merchandiser', 'Sampling', { b: 1, a: 1 }),
  act('A05', 'Fit sample submission', 'Fit Sub', 'Sampling', 'Merchandiser', 'Sampling'),
  act('A06', 'Fit sample approval', 'Fit App', 'Approval', 'Merchandiser', 'Sampling', { b: 1, a: 1 }),
  act('A07', 'Quality (fabric) submission', 'Fab Test Sub', 'Quality', 'QC', 'Sampling'),
  act('A08', 'Quality (fabric) approval', 'Fab Test App', 'Quality', 'QC', 'QC', { a: 1 }),
  act('A09', 'First Bulk Piece', 'FBP', 'Sampling', 'Merchandiser', 'Manual', { m: 1 }),
  act('A10', 'PP sample submission', 'PP Sub', 'Sampling', 'Merchandiser', 'Sampling'),
  act('A11', 'PP sample approval', 'PP App', 'Approval', 'Merchandiser', 'Sampling', { m: 1, b: 1, a: 1 }),
  act('A12', 'Pattern grading', 'Grading', 'Production', 'CAD Room', 'Manual'),
  act('A13', 'Bulk fabric in-house', 'Fabric In', 'Material', 'Store Keeper', 'Store', { m: 1 }),
  act('A14', 'Fabric testing / inspection', 'Fab Inspect', 'Quality', 'QC', 'QC', { a: 1 }),
  act('A15', 'CAD marker / bulk programme', 'CAD Marker', 'Production', 'CAD Room', 'Manual'),
  act('A16', 'PP meeting', 'PP Meet', 'Production', 'Production Planner', 'Manual', { a: 1 }),
  act('A17', 'Cutting', 'Cutting', 'Production', 'Cutting Master', 'Production', { m: 1 }),
  act('A18', 'Embroidery', 'Emb', 'Production', 'Production Manager', 'Production'),
  act('A19', 'Printing', 'Print', 'Production', 'Production Manager', 'Production'),
  act('A20', 'Stitching', 'Stitching', 'Production', 'Production Manager', 'Production', { m: 1 }),
  act('A21', 'Finishing', 'Finishing', 'Production', 'Production Manager', 'Production'),
  act('A22', 'Packing', 'Packing', 'Production', 'Production Manager', 'Production'),
  act('A23', 'Final inspection', 'Final AQL', 'Quality', 'QC', 'QC', { m: 1, a: 1 }),
  act('A24', 'Dispatch / Handover', 'Dispatch', 'Shipment', 'Merchandiser', 'Shipment', { m: 1 }),
];

// ── Template lines (§7.3 / §7.5) ────────────────────────────────────────────
const line = (code, preds, baseDays, pct, min, max, fixed, extra = {}) => ({
  code, predecessors: preds, baseDays, durationPct: pct, minDays: min, maxDays: max,
  fixed: !!fixed, conditionalOnRoute: !!extra.route, routeOperation: extra.route || null,
  reminderLeadDays: extra.remind ?? 2, escalationAfterDays: extra.esc ?? 2,
  allowManualActual: true, completionThresholdPct: extra.threshold ?? 100,
});

export const baselineLines = [
  line('A01', [], 0, 0, 0, 0, true),
  line('A02', ['A01'], 7, 7.87, 3, 14, false),
  line('A03', ['A01'], 10, 11.24, 5, 20, false),
  line('A04', ['A03'], 7, 7.87, 5, 14, false, { remind: 3 }),
  line('A05', ['A01'], 15, 16.85, 7, 25, false),
  line('A06', ['A05'], 7, 7.87, 5, 14, false, { remind: 3 }),
  line('A07', ['A04'], 7, 7.87, 3, 14, false),
  line('A08', ['A07'], 7, 7.87, 5, 14, false),
  line('A09', ['A04'], 25, 28.09, 15, 40, false, { remind: 5 }),
  line('A10', ['A09'], 6, 6.74, 3, 12, false),
  line('A11', ['A10'], 7, 7.87, 5, 14, false, { remind: 3 }),
  line('A12', ['A11'], 3, 3.37, 2, 6, false),
  line('A13', ['A02', 'A08', 'A11'], 10, 11.24, 7, 25, false, { remind: 5 }),
  line('A14', ['A13'], 2, 2.25, 2, 2, true),
  line('A15', ['A12', 'A14'], 7, 7.87, 3, 12, false),
  line('A16', ['A15'], 1, 1.12, 1, 1, true),
  line('A17', ['A16'], 3, 3.37, 2, 8, false, { threshold: 95 }),
  line('A18', ['A17'], 0, 0, 0, 0, false, { route: 'Embroidery' }),
  line('A19', ['A17'], 0, 0, 0, 0, false, { route: 'Printing' }),
  line('A20', ['A17', 'A18', 'A19'], 5, 5.62, 3, 20, false, { threshold: 95 }),
  line('A21', ['A20'], 3, 3.37, 2, 8, false),
  line('A22', ['A21'], 2, 2.25, 2, 6, false),
  line('A23', ['A22'], 1, 1.12, 1, 1, true),
  line('A24', ['A23'], 0, 0, 0, 0, true),
];

// Activewear variant — printing route carries real durations.
const activewearLines = baselineLines.map((l) => (l.code === 'A19'
  ? { ...l, baseDays: 4, durationPct: 4.49, minDays: 2, maxDays: 8 }
  : l));

export const seedTemplates = [
  { id: 1, templateCode: 'TPL-GLOBAL', templateName: 'Global Default — All Buyers', buyer: null, productType: null, status: 'ACTIVE', version: 3, effectiveFrom: '2026-06-01', lines: baselineLines },
  { id: 2, templateCode: 'TPL-HM-NIGHT', templateName: 'Nightwear — H&M', buyer: 'H&M', productType: 'Nightwear', status: 'ACTIVE', version: 2, effectiveFrom: '2026-07-01', lines: baselineLines },
  { id: 3, templateCode: 'TPL-ACTIVE', templateName: 'Activewear — Any Buyer', buyer: null, productType: 'Activewear', status: 'ACTIVE', version: 1, effectiveFrom: '2026-07-15', lines: activewearLines },
];

// ── Orders (§8.1 inputs) — receivedAgo/leadtime in days relative to today ──
// actuals: { through: last completed code (sequence order), late: {code: +days} }
export const seedOrders = [
  { id: 1, orderNo: 'ORD-2611', buyer: 'H&M', styleNo: 'HM-NW-4471', productType: 'Nightwear', qty: 24000, uom: 'Pcs', merchandiser: 'Priya S', receivedAgo: 46, leadtime: 84, routeOps: [], actuals: { through: 'A09', late: { A04: 2, A09: 1 } } },
  { id: 2, orderNo: 'ORD-2612', buyer: 'Zara', styleNo: 'ZR-WT-1180', productType: 'Woven Tops', qty: 8500, uom: 'Pcs', merchandiser: 'Arun K', receivedAgo: 18, leadtime: 90, routeOps: [], actuals: { through: 'A03', late: {} } },
  { id: 3, orderNo: 'ORD-2613', buyer: 'Decathlon', styleNo: 'DC-AW-3327', productType: 'Activewear', qty: 32000, uom: 'Pcs', merchandiser: 'Meena R', receivedAgo: 32, leadtime: 62, routeOps: ['Printing'], actuals: { through: 'A08', late: {} } },
  { id: 4, orderNo: 'ORD-2614', buyer: 'Primark', styleNo: 'PR-KD-2205', productType: 'Kidswear', qty: 15000, uom: 'Pcs', merchandiser: 'Priya S', receivedAgo: 8, leadtime: 50, routeOps: [], actuals: { through: 'A01', late: {} } },
  { id: 5, orderNo: 'ORD-2615', buyer: 'M&S', styleNo: 'MS-NW-0918', productType: 'Nightwear', qty: 12000, uom: 'Pcs', merchandiser: 'Arun K', receivedAgo: 60, leadtime: 88, routeOps: ['Embroidery'], actuals: { through: 'A11', late: { A06: 4, A11: 6 } } },
  { id: 6, orderNo: 'ORD-2616', buyer: 'Uniqlo', styleNo: 'UQ-LG-5540', productType: 'Loungewear', qty: 40000, uom: 'Pcs', merchandiser: 'Meena R', receivedAgo: 25, leadtime: 75, routeOps: [], actuals: { through: 'A04', late: { A04: 5 } } },
  { id: 7, orderNo: 'ORD-2617', buyer: 'Tesco F&F', styleNo: 'TF-KD-7702', productType: 'Kidswear', qty: 18000, uom: 'Pcs', merchandiser: 'Sanjay V', receivedAgo: 40, leadtime: 70, routeOps: [], actuals: { through: 'A08', late: { A03: 1 } } },
  { id: 8, orderNo: 'ORD-2618', buyer: 'H&M', styleNo: 'HM-AW-9915', productType: 'Activewear', qty: 27500, uom: 'Pcs', merchandiser: 'Priya S', receivedAgo: 12, leadtime: 95, routeOps: ['Printing'], actuals: { through: 'A02', late: {} } },
  { id: 9, orderNo: 'ORD-2619', buyer: 'C&A', styleNo: 'CA-WT-6633', productType: 'Woven Tops', qty: 9800, uom: 'Pcs', merchandiser: 'Sanjay V', receivedAgo: 70, leadtime: 84, routeOps: [], actuals: { through: 'A16', late: { A13: 3 } } },
  { id: 10, orderNo: 'ORD-2620', buyer: 'Zara', styleNo: 'ZR-NW-2244', productType: 'Nightwear', qty: 6500, uom: 'Pcs', merchandiser: 'Meena R', receivedAgo: 95, leadtime: 90, routeOps: [], actuals: { through: 'A22', late: { A20: 2 } }, planStatus: 'ON_HOLD' },
  { id: 11, orderNo: 'ORD-2621', buyer: 'M&S', styleNo: 'MS-LG-8830', productType: 'Loungewear', qty: 21000, uom: 'Pcs', merchandiser: 'Arun K', receivedAgo: 110, leadtime: 92, routeOps: [], actuals: { through: 'A24', late: {} }, planStatus: 'COMPLETED' },
  { id: 12, orderNo: 'ORD-2622', buyer: 'Uniqlo', styleNo: 'UQ-KD-1101', productType: 'Kidswear', qty: 30000, uom: 'Pcs', merchandiser: 'Sanjay V', receivedAgo: 5, leadtime: 58, routeOps: [], actuals: { through: 'A01', late: {} } },
];

// ── Re-plan requests (§13) ──────────────────────────────────────────────────
export const seedReplans = [
  { id: 1, planId: 1, activityCode: 'A13', proposedShiftDays: 4, reasonCode: 'Fabric delay', justification: 'Mill confirmed greige delay of 4 days; dyeing slot rebooked.', workflowStatus: 'PENDING_APPROVAL', raisedBy: 'Priya S', raisedAgo: 1 },
  { id: 2, planId: 6, activityCode: 'A06', proposedShiftDays: 3, reasonCode: 'Buyer approval delay', justification: 'Buyer fit comments pending since Monday; chaser sent.', workflowStatus: 'PENDING_APPROVAL', raisedBy: 'Meena R', raisedAgo: 2 },
  { id: 3, planId: 3, activityCode: 'A15', proposedShiftDays: 2, reasonCode: 'Capacity constraint', justification: 'CAD room loaded with ORD-2618 markers.', workflowStatus: 'RETURNED', raisedBy: 'Meena R', raisedAgo: 4, approverRemarks: 'Split the marker job instead — confirm with CAD room first.' },
];

export const MERCHANDISERS = ['Priya S', 'Arun K', 'Meena R', 'Sanjay V'];
export const PRODUCT_TYPES = ['Nightwear', 'Woven Tops', 'Activewear', 'Kidswear', 'Loungewear'];
export const CURRENT_USER = 'Priya S';
